# News Category Prediction — Approche LLM avec Ollama

Ce notebook reprend le même dataset et les mêmes objectifs que le notebook de référence (classification d'articles HuffPost en catégories), mais remplace le pipeline NLP classique (TF-IDF + Logistic Regression) par une **prédiction via un LLM local** servi par **Ollama**.

### Approches testées
1. **Zero-shot** : on donne la liste des catégories et le texte, le LLM prédit.
2. **Few-shot** : on ajoute quelques exemples dans le prompt pour guider le modèle.
3. **Évaluation** : Accuracy et MRR@k, identiques au notebook de référence.

### Prérequis
- [Ollama](https://ollama.ai) installé et lancé (`ollama serve`)
- Un modèle téléchargé, par ex. `ollama pull llama3.1:8b` ou `mistral`

---
## 1. Installation & Imports

In [1]:
import pandas as pd
import numpy as np
import json
import re
import time
import logging
from tqdm import tqdm
from sklearn.model_selection import train_test_split

import ollama

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

---
## 2. Configuration Ollama

In [2]:
# ---- Configuration ----
OLLAMA_MODEL = "llama3.1:8b"
EVAL_SAMPLE_SIZE = 200
TOP_K = 3

# Vérifier que Ollama est joignable
try:
    response = ollama.list()
    print("Ollama est connecté. Modèles disponibles :")
    # Afficher la structure pour debug
    print(type(response))
    print(response)
except Exception as e:
    print(f"Erreur de connexion à Ollama : {e}")

2026-05-06 15:37:08,998 : INFO : HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"

Ollama est connecté. Modèles disponibles :
<class 'ollama._types.ListResponse'>
models=[Model(model='llama3.1:8b', modified_at=datetime.datetime(2026, 4, 14, 22, 26, 0, 102035, tzinfo=TzInfo(7200)), digest='46e0c10c039e019119339687c3c1757cc81b9da49709a3b3924863ba87ca666e', size=4920753328, details=ModelDetails(parent_model='', format='gguf', family='llama', families=['llama'], parameter_size='8.0B', quantization_level='Q4_K_M'))]

---
## 3. Chargement des données

In [3]:
df = pd.read_json(r"C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\data\news_category_dataset.json", lines=True)
print(f"Nombre d'articles : {len(df)}")
print(f"Colonnes : {list(df.columns)}")
df.head(3)

Nombre d'articles : 124989
Colonnes : ['short_description', 'headline', 'date', 'link', 'authors', 'category']

,short_description,headline,date,link,authors,category
0,She left her husband. He killed their children...,There Were 2 Mass Shootings In Texas Last Week...,2018-05-26,https://www.huffingtonpost.com/entry/texas-ama...,Melissa Jeltsen,CRIME
1,Of course it has a song.,Will Smith Joins Diplo And Nicky Jam For The 2...,2018-05-26,https://www.huffingtonpost.com/entry/will-smit...,Andy McDonald,ENTERTAINMENT
2,The actor and his longtime girlfriend Anna Ebe...,Hugh Grant Marries For The First Time At Age 57,2018-05-26,https://www.huffingtonpost.com/entry/hugh-gran...,Ron Dicker,ENTERTAINMENT

In [4]:
# Liste des catégories du dataset
CATEGORIES = sorted(df['category'].unique().tolist())
print(f"Nombre de catégories : {len(CATEGORIES)}")
print(CATEGORIES)

# Fusion WORLDPOST / THE WORLDPOST (catégories identiques dans HuffPost)
df['category'] = df['category'].replace({'THE WORLDPOST': 'WORLDPOST'})
CATEGORIES = sorted(df['category'].unique().tolist())
print(f"\nAprès fusion WORLDPOST : {len(CATEGORIES)} catégories")
print(CATEGORIES)

Nombre de catégories : 31
['ARTS', 'ARTS & CULTURE', 'BLACK VOICES', 'BUSINESS', 'COLLEGE', 'COMEDY', 'CRIME', 'EDUCATION', 'ENTERTAINMENT', 'FIFTY', 'GOOD NEWS', 'GREEN', 'HEALTHY LIVING', 'IMPACT', 'LATINO VOICES', 'MEDIA', 'PARENTS', 'POLITICS', 'QUEER VOICES', 'RELIGION', 'SCIENCE', 'SPORTS', 'STYLE', 'TASTE', 'TECH', 'THE WORLDPOST', 'TRAVEL', 'WEIRD NEWS', 'WOMEN', 'WORLD NEWS', 'WORLDPOST']

Après fusion WORLDPOST : 30 catégories
['ARTS', 'ARTS & CULTURE', 'BLACK VOICES', 'BUSINESS', 'COLLEGE', 'COMEDY', 'CRIME', 'EDUCATION', 'ENTERTAINMENT', 'FIFTY', 'GOOD NEWS', 'GREEN', 'HEALTHY LIVING', 'IMPACT', 'LATINO VOICES', 'MEDIA', 'PARENTS', 'POLITICS', 'QUEER VOICES', 'RELIGION', 'SCIENCE', 'SPORTS', 'STYLE', 'TASTE', 'TECH', 'TRAVEL', 'WEIRD NEWS', 'WOMEN', 'WORLD NEWS', 'WORLDPOST']

In [5]:
# Descriptions explicites pour les catégories aux noms opaques (propres à HuffPost)
# Sans ces descriptions, le LLM ne peut pas deviner ce que signifie "FIFTY", "GREEN", "TASTE"...
CATEGORY_DESCRIPTIONS = {
    "FIFTY": "life, lifestyle and issues for people over 50 years old",
    "GREEN": "environment, ecology, sustainability and climate",
    "WORLDPOST": "international news and global perspectives",
    "TASTE": "food, recipes, cooking, restaurants and culinary experiences",
    "IMPACT": "social impact, activism and humanitarian causes",
    "WOMEN": "women's rights, issues and perspectives",
    "BLACK VOICES": "news and perspectives from the Black community",
    "LATINO VOICES": "news and perspectives from the Latino community",
    "QUEER VOICES": "LGBTQ+ news, rights and perspectives",
    "GOOD NEWS": "positive and uplifting news stories",
    "WEIRD NEWS": "unusual, bizarre or offbeat news stories",
    "COLLEGE": "college life, higher education and campus news",
    "MEDIA": "journalism, television, newspapers and media industry news",
}

def format_categories_for_prompt(categories: list) -> str:
    """Formate les catégories avec leurs descriptions pour le prompt."""
    lines = []
    for c in categories:
        if c in CATEGORY_DESCRIPTIONS:
            lines.append(f"- {c}: {CATEGORY_DESCRIPTIONS[c]}")
        else:
            lines.append(f"- {c}")
    return "\n".join(lines)

print("Exemple de formatage des catégories :")
print(format_categories_for_prompt(CATEGORIES[:8]))

Exemple de formatage des catégories :
- ARTS
- ARTS & CULTURE
- BLACK VOICES: news and perspectives from the Black community
- BUSINESS
- COLLEGE: college life, higher education and campus news
- COMEDY
- CRIME
- EDUCATION

def tokenize_url(url: str):
    url = url.replace("https://www.huffingtonpost.com/entry/", "")
    url = re.sub(r"(\W|_)+", " ", url)
    return url

df['tokenized_url'] = df['link'].apply(tokenize_url)

# Ordre identique au notebook de référence : description en premier (signal le plus riche),
# puis headline, puis URL — la description contient le corps de l'article
df['text'] = df['short_description'] + '. ' + df['headline'] + '. ' + df['tokenized_url']
df['text'] = df['text'].fillna('')

df[['category', 'headline', 'short_description', 'text']].sample(5)

In [6]:
def tokenize_url(url: str):
    url = url.replace("https://www.huffingtonpost.com/entry/", "")
    url = re.sub(r"(\W|_)+", " ", url)
    return url

df['tokenized_url'] = df['link'].apply(tokenize_url)

# Texte combiné : headline + description + URL tokenisée (signal supplémentaire)
df['text'] = df['headline'] + '. ' + df['short_description'] + '. ' + df['tokenized_url']
df['text'] = df['text'].fillna('')

df[['category', 'headline', 'short_description', 'text']].sample(5)

,category,headline,short_description,text
976,BUSINESS,Bank Of America Appears To Flip On Firearm Pro...,The bank pledged in April to stop financing co...,Bank Of America Appears To Flip On Firearm Pro...
71505,SPORTS,The Odell Beckham-Josh Norman Matchup Was Ever...,And more!,The Odell Beckham-Josh Norman Matchup Was Ever...
121076,POLITICS,An Urban Agenda at the United Nations (VIDEO),This increase in population growth brings seve...,An Urban Agenda at the United Nations (VIDEO)....
87447,WOMEN,9 Harrowing Images That Capture The Lasting Im...,,9 Harrowing Images That Capture The Lasting Im...
54208,POLITICS,Donald Trump Meets Joni Ernst Amid Vice Presid...,"Other possible VP picks include Newt Gingrich,...",Donald Trump Meets Joni Ernst Amid Vice Presid...

### Split train / test

In [ ]:
# ---- Index TF-IDF pour le few-shot dynamique ----
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

logging.info("Construction de l'index TF-IDF sur le train set...")
tfidf_vectorizer = TfidfVectorizer(max_df=0.95)
train_vectors = tfidf_vectorizer.fit_transform(training_data['text'].values)
# Convertir en array pour accès rapide par index
training_data_reset = training_data.reset_index(drop=True)
logging.info(f"Index construit : {train_vectors.shape[0]} documents, {train_vectors.shape[1]} features.")

def get_dynamic_examples(article_text: str, n_examples: int = 5) -> list:
    """
    Récupère les n articles les plus similaires dans le train set
    via similarité cosine TF-IDF, pour construire des exemples few-shot pertinents.
    """
    article_vec = tfidf_vectorizer.transform([article_text])
    sims = cosine_similarity(article_vec, train_vectors)[0]
    top_indices = sims.argsort()[-n_examples:][::-1]
    return [
        {
            "text": training_data_reset.iloc[i]['text'][:200],
            "category": training_data_reset.iloc[i]['category']
        }
        for i in top_indices
    ]

# Démonstration sur le premier article d'évaluation
test_article = eval_data.iloc[0]['text']
print(f"Article : {test_article[:100]}...\n")
print("Top-5 exemples dynamiques trouvés :")
for ex in get_dynamic_examples(test_article, n_examples=5):
    print(f"  [{ex['category']}] {ex['text'][:80]}...")

In [7]:
training_data, testing_data = train_test_split(df, random_state=2000)
print(f"Train : {len(training_data)} | Test : {len(testing_data)}")

# Sous-échantillonnage du test pour l'évaluation LLM (coût en temps)
eval_data = testing_data.sample(n=min(EVAL_SAMPLE_SIZE, len(testing_data)), random_state=42).reset_index(drop=True)
print(f"Échantillon d'évaluation : {len(eval_data)} articles")

Train : 93741 | Test : 31248
Échantillon d'évaluation : 200 articles

def build_zero_shot_prompt(text: str, categories: list, top_k: int = 3) -> str:
    """Construit un prompt zero-shot avec chain-of-thought."""
    cats_str = format_categories_for_prompt(categories)
    prompt = f"""You are a news article classifier. Your task is to assign the most appropriate category to a news article.

CATEGORIES:
{cats_str}

ARTICLE:
\"\"\"
{text}
\"\"\"

Think step by step:
1. Identify the main topic and key entities in the article.
2. Match those topics to the most relevant categories from the list above.
3. Rank your top {top_k} choices from most likely to least likely.

Then respond ONLY with a JSON array of strings, nothing else. Example: ["POLITICS", "BUSINESS", "CRIME"]
"""
    return prompt


def build_few_shot_prompt(text: str, categories: list, examples: list, top_k: int = 3) -> str:
    """Construit un prompt few-shot avec chain-of-thought."""
    cats_str = format_categories_for_prompt(categories)

    examples_str = ""
    for ex in examples:
        examples_str += f'Article: "{ex["text"]}"\nCategory: {ex["category"]}\n\n'

    prompt = f"""You are a news article classifier. Your task is to assign the most appropriate category to a news article.

CATEGORIES:
{cats_str}

Here are some examples:

{examples_str}
Now classify this article:

ARTICLE:
\"\"\"
{text}
\"\"\"

Think step by step:
1. Identify the main topic and key entities in the article.
2. Compare with the examples above to find similar patterns.
3. Match those topics to the most relevant categories from the list above.
4. Rank your top {top_k} choices from most likely to least likely.

Then respond ONLY with a JSON array of strings, nothing else. Example: ["POLITICS", "BUSINESS", "CRIME"]
"""
    return prompt


print("Exemple de prompt zero-shot (avec chain-of-thought) :")
print(build_zero_shot_prompt("Biden announces new climate policy for 2025", CATEGORIES[:5], top_k=3))

In [ ]:
def predict_with_ollama(text: str, categories: list, model: str = OLLAMA_MODEL,
                         top_k: int = 3, mode: str = "zero_shot",
                         examples: list = None, n_dynamic: int = 5) -> list:
    """
    Appelle Ollama pour prédire les catégories d'un texte.

    Args:
        text: le texte de l'article
        categories: liste des catégories possibles
        model: nom du modèle Ollama
        top_k: nombre de catégories à retourner
        mode: 'zero_shot', 'few_shot' ou 'dynamic_few_shot'
        examples: liste de dicts {text, category} pour le few-shot statique
        n_dynamic: nombre d'exemples pour le few-shot dynamique

    Returns:
        Liste de catégories prédites (top_k)
    """
    if mode == "dynamic_few_shot":
        dynamic_examples = get_dynamic_examples(text, n_examples=n_dynamic)
        prompt = build_few_shot_prompt(text, categories, dynamic_examples, top_k)
    elif mode == "few_shot" and examples:
        prompt = build_few_shot_prompt(text, categories, examples, top_k)
    else:
        prompt = build_zero_shot_prompt(text, categories, top_k)

    try:
        response = ollama.chat(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            options={
                "temperature": 0.0,   # Déterministe pour reproductibilité
                "num_predict": 200,   # Chain-of-thought nécessite plus de tokens
            }
        )
        response_text = response['message']['content']
        return parse_llm_response(response_text, categories, top_k)

    except Exception as e:
        logging.error(f"Erreur Ollama : {e}")
        return []

In [9]:
def parse_llm_response(response_text: str, valid_categories: list, top_k: int = 3) -> list:
    """
    Parse la réponse du LLM pour en extraire les catégories prédites.
    Gère les formats variés que le LLM peut retourner.
    """
    text = response_text.strip()

    # Tenter le parsing JSON direct
    try:
        json_match = re.search(r'\[.*?\]', text, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group())
            preds = [p.strip().upper() for p in parsed if isinstance(p, str)]
            preds = [p for p in preds if p in valid_categories]
            if preds:
                return preds[:top_k]
    except (json.JSONDecodeError, AttributeError):
        pass

    # Fallback : chercher les catégories dans l'ordre d'apparition dans le texte
    text_upper = text.upper()
    found = [cat for cat in valid_categories if cat in text_upper]
    if found:
        # Trier par ordre d'apparition (pas alphabétique) pour préserver le ranking du modèle
        found.sort(key=lambda c: text_upper.index(c))
        return found[:top_k]

    return []


# Test du parser
test_responses = [
    '["POLITICS", "CRIME", "BUSINESS"]',
    'The article is about POLITICS and CRIME.',
    'Here are my predictions:\n["ENTERTAINMENT", "COMEDY"]',
]
for resp in test_responses:
    print(f"  Input:  {resp!r}")
    print(f"  Parsed: {parse_llm_response(resp, CATEGORIES)}")
    print()

  Input:  '["POLITICS", "CRIME", "BUSINESS"]'
  Parsed: ['POLITICS', 'CRIME', 'BUSINESS']

  Input:  'The article is about POLITICS and CRIME.'
  Parsed: ['POLITICS', 'CRIME']

  Input:  'Here are my predictions:\n["ENTERTAINMENT", "COMEDY"]'
  Parsed: ['ENTERTAINMENT', 'COMEDY']

In [10]:
def predict_with_ollama(text: str, categories: list, model: str = OLLAMA_MODEL,
                         top_k: int = 3, mode: str = "zero_shot",
                         examples: list = None) -> list:
    """
    Appelle Ollama pour prédire les catégories d'un texte.
    
    Args:
        text: le texte de l'article
        categories: liste des catégories possibles
        model: nom du modèle Ollama
        top_k: nombre de catégories à retourner
        mode: 'zero_shot' ou 'few_shot'
        examples: liste de dicts {text, category} pour le few-shot
    
    Returns:
        Liste de catégories prédites (top_k)
    """
    if mode == "few_shot" and examples:
        prompt = build_few_shot_prompt(text, categories, examples, top_k)
    else:
        prompt = build_zero_shot_prompt(text, categories, top_k)
    
    try:
        response = ollama.chat(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            options={
                "temperature": 0.1,  # Basse température pour des prédictions stables
                "num_predict": 100,  # On n'a besoin que de quelques tokens
            }
        )
        response_text = response['message']['content']
        return parse_llm_response(response_text, categories, top_k)
    
    except Exception as e:
        logging.error(f"Erreur Ollama : {e}")
        return []

### Test rapide sur un article

In [11]:
# Test sur un article du dataset
sample = eval_data.iloc[0]
print(f"Texte  : {sample['text'][:200]}...")
print(f"Vrai   : {sample['category']}")

pred = predict_with_ollama(sample['text'], CATEGORIES, top_k=TOP_K)
print(f"Prédit : {pred}")

Texte  : Trump Admin Plans To Impose 20 Percent Duties On Canadian Softwood Lumber. The move escalates a long-running trade dispute between the two countries.. canada softwood lumber duties us 58fe91c1e4b06b9c...
Vrai   : POLITICS

2026-05-06 15:38:22,553 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Prédit : ['POLITICS', 'BUSINESS', 'WORLD NEWS']

---
## 5. Fonctions d'évaluation (reprises du notebook de référence)

In [12]:
def _reciprocal_rank(true_labels: list, machine_preds: list):
    """Compute the reciprocal rank at cutoff k"""
    tp_pos_list = [(idx + 1) for idx, r in enumerate(machine_preds) if r in true_labels]
    rr = 0
    if len(tp_pos_list) > 0:
        first_pos_list = tp_pos_list[0]
        rr = 1 / float(first_pos_list)
    return rr


def compute_mrr_at_k(items: list):
    """Compute the MRR (average RR) at cutoff k"""
    rr_total = 0
    for item in items:
        rr_at_k = _reciprocal_rank(item[0], item[1])
        rr_total += rr_at_k
    mrr = rr_total / float(len(items))
    return mrr


def compute_accuracy(eval_items: list):
    """Accuracy : le vrai label est-il dans les top-k prédictions ?"""
    correct = 0
    for item in eval_items:
        true_pred = item[0]
        machine_pred = set(item[1])
        for cat in true_pred:
            if cat in machine_pred:
                correct += 1
                break
    accuracy = correct / float(len(eval_items))
    return accuracy


def collect_preds(y_true: list, y_preds: list):
    return [[[y_true[idx]], pred] for idx, pred in enumerate(y_preds)]

---
## 6. Évaluation Zero-Shot

In [13]:
def run_evaluation(eval_df: pd.DataFrame, categories: list, model: str = OLLAMA_MODEL,
                   top_k: int = 3, mode: str = "zero_shot", examples: list = None):
    """
    Lance la prédiction LLM sur un DataFrame et calcule les métriques.
    """
    all_preds = []
    y_true = eval_df['category'].values.tolist()
    
    start_time = time.time()
    
    for idx, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc=f"Prédiction ({mode})"):
        preds = predict_with_ollama(
            text=row['text'],
            categories=categories,
            model=model,
            top_k=top_k,
            mode=mode,
            examples=examples
        )
        all_preds.append(preds)
    
    elapsed = time.time() - start_time
    
    # Calcul des métriques
    eval_items = collect_preds(y_true, all_preds)
    accuracy = compute_accuracy(eval_items)
    mrr = compute_mrr_at_k(eval_items)
    
    # Accuracy top-1 (la première prédiction est-elle correcte ?)
    top1_correct = sum(1 for true, pred in zip(y_true, all_preds) if pred and pred[0] == true)
    top1_acc = top1_correct / len(y_true)
    
    # Taux d'échec (le LLM n'a retourné aucune catégorie valide)
    empty_preds = sum(1 for p in all_preds if len(p) == 0)
    
    results = {
        "mode": mode,
        "model": model,
        "n_samples": len(eval_df),
        "top_k": top_k,
        "accuracy_at_k": accuracy,
        "top1_accuracy": top1_acc,
        "mrr_at_k": mrr,
        "empty_predictions": empty_preds,
        "time_seconds": round(elapsed, 1),
        "seconds_per_article": round(elapsed / len(eval_df), 2),
    }
    
    return results, all_preds


print("Fonction d'évaluation prête.")

Fonction d'évaluation prête.

In [14]:
# ---- Évaluation Zero-Shot ----
logging.info(f"Lancement évaluation zero-shot sur {len(eval_data)} articles...")

results_zs, preds_zs = run_evaluation(
    eval_df=eval_data,
    categories=CATEGORIES,
    model=OLLAMA_MODEL,
    top_k=TOP_K,
    mode="zero_shot"
)

print("\n=== Résultats Zero-Shot ===")
for k, v in results_zs.items():
    print(f"  {k:25s} : {v}")

2026-05-06 15:38:22,607 : INFO : Lancement évaluation zero-shot sur 200 articles...
Prédiction (zero_shot):   0%|          | 0/200 [00:00<?, ?it/s]2026-05-06 15:38:24,308 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   0%|          | 1/200 [00:01<05:36,  1.69s/it]2026-05-06 15:38:26,767 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   1%|          | 2/200 [00:04<07:04,  2.14s/it]2026-05-06 15:38:28,889 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   2%|▏         | 3/200 [00:06<07:00,  2.13s/it]2026-05-06 15:38:31,518 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   2%|▏         | 4/200 [00:08<07:36,  2.33s/it]2026-05-06 15:38:33,644 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   2%|▎         | 5/200 [00:11<07:19,  2.26s/it]2026-05-06 15:38:35,724 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   3%|▎         | 6/200 [00:13<07:05,  2.20s/it]2026-05-06 15:38:37,401 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   4%|▎         | 7/200 [00:14<06:31,  2.03s/it]2026-05-06 15:38:38,983 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   4%|▍         | 8/200 [00:16<06:01,  1.88s/it]2026-05-06 15:38:40,959 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   4%|▍         | 9/200 [00:18<06:05,  1.91s/it]2026-05-06 15:38:43,544 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   5%|▌         | 10/200 [00:20<06:42,  2.12s/it]2026-05-06 15:38:46,110 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   6%|▌         | 11/200 [00:23<07:06,  2.26s/it]2026-05-06 15:38:48,422 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   6%|▌         | 12/200 [00:25<07:07,  2.27s/it]2026-05-06 15:38:50,485 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   6%|▋         | 13/200 [00:27<06:53,  2.21s/it]2026-05-06 15:38:53,021 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   7%|▋         | 14/200 [00:30<07:09,  2.31s/it]2026-05-06 15:38:54,626 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   8%|▊         | 15/200 [00:32<06:27,  2.10s/it]2026-05-06 15:38:56,638 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   8%|▊         | 16/200 [00:34<06:21,  2.07s/it]2026-05-06 15:38:59,191 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   8%|▊         | 17/200 [00:36<06:45,  2.22s/it]2026-05-06 15:39:00,919 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   9%|▉         | 18/200 [00:38<06:16,  2.07s/it]2026-05-06 15:39:02,771 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  10%|▉         | 19/200 [00:40<06:02,  2.00s/it]2026-05-06 15:39:04,320 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  10%|█         | 20/200 [00:41<05:36,  1.87s/it]2026-05-06 15:39:06,327 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  10%|█         | 21/200 [00:43<05:41,  1.91s/it]2026-05-06 15:39:08,102 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  11%|█         | 22/200 [00:45<05:32,  1.87s/it]2026-05-06 15:39:10,372 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  12%|█▏        | 23/200 [00:47<05:52,  1.99s/it]2026-05-06 15:39:12,545 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  12%|█▏        | 24/200 [00:49<05:59,  2.04s/it]2026-05-06 15:39:14,024 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  12%|█▎        | 25/200 [00:51<05:28,  1.87s/it]2026-05-06 15:39:15,905 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  13%|█▎        | 26/200 [00:53<05:26,  1.88s/it]2026-05-06 15:39:17,834 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  14%|█▎        | 27/200 [00:55<05:27,  1.89s/it]2026-05-06 15:39:19,557 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  14%|█▍        | 28/200 [00:56<05:16,  1.84s/it]2026-05-06 15:39:21,875 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  14%|█▍        | 29/200 [00:59<05:39,  1.98s/it]2026-05-06 15:39:24,373 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  15%|█▌        | 30/200 [01:01<06:03,  2.14s/it]2026-05-06 15:39:26,236 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  16%|█▌        | 31/200 [01:03<05:47,  2.06s/it]2026-05-06 15:39:28,283 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  16%|█▌        | 32/200 [01:05<05:44,  2.05s/it]2026-05-06 15:39:30,359 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  16%|█▋        | 33/200 [01:07<05:44,  2.06s/it]2026-05-06 15:39:31,909 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  17%|█▋        | 34/200 [01:09<05:16,  1.91s/it]2026-05-06 15:39:33,935 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  18%|█▊        | 35/200 [01:11<05:20,  1.94s/it]2026-05-06 15:39:36,168 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  18%|█▊        | 36/200 [01:13<05:32,  2.03s/it]2026-05-06 15:39:38,315 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  18%|█▊        | 37/200 [01:15<05:36,  2.07s/it]2026-05-06 15:39:39,929 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  19%|█▉        | 38/200 [01:17<05:12,  1.93s/it]2026-05-06 15:39:44,527 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  20%|█▉        | 39/200 [01:21<07:19,  2.73s/it]2026-05-06 15:39:46,652 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  20%|██        | 40/200 [01:24<06:47,  2.55s/it]2026-05-06 15:39:48,725 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  20%|██        | 41/200 [01:26<06:22,  2.41s/it]2026-05-06 15:39:50,485 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  21%|██        | 42/200 [01:27<05:49,  2.21s/it]2026-05-06 15:39:53,166 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  22%|██▏       | 43/200 [01:30<06:09,  2.35s/it]2026-05-06 15:39:54,775 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  22%|██▏       | 44/200 [01:32<05:32,  2.13s/it]2026-05-06 15:39:56,822 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  22%|██▎       | 45/200 [01:34<05:26,  2.10s/it]2026-05-06 15:39:58,674 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  23%|██▎       | 46/200 [01:36<05:12,  2.03s/it]2026-05-06 15:40:00,907 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  24%|██▎       | 47/200 [01:38<05:19,  2.09s/it]2026-05-06 15:40:03,495 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  24%|██▍       | 48/200 [01:40<05:40,  2.24s/it]2026-05-06 15:40:05,805 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  24%|██▍       | 49/200 [01:43<05:41,  2.26s/it]2026-05-06 15:40:07,845 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  25%|██▌       | 50/200 [01:45<05:29,  2.19s/it]2026-05-06 15:40:09,712 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  26%|██▌       | 51/200 [01:47<05:12,  2.10s/it]2026-05-06 15:40:11,847 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  26%|██▌       | 52/200 [01:49<05:11,  2.11s/it]2026-05-06 15:40:14,317 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  26%|██▋       | 53/200 [01:51<05:25,  2.22s/it]2026-05-06 15:40:16,798 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  27%|██▋       | 54/200 [01:54<05:35,  2.30s/it]2026-05-06 15:40:19,224 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  28%|██▊       | 55/200 [01:56<05:38,  2.33s/it]2026-05-06 15:40:21,459 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  28%|██▊       | 56/200 [01:58<05:31,  2.30s/it]2026-05-06 15:40:23,394 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  28%|██▊       | 57/200 [02:00<05:13,  2.19s/it]2026-05-06 15:40:24,857 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  29%|██▉       | 58/200 [02:02<04:40,  1.97s/it]2026-05-06 15:40:26,995 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  30%|██▉       | 59/200 [02:04<04:45,  2.02s/it]2026-05-06 15:40:28,914 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  30%|███       | 60/200 [02:06<04:38,  1.99s/it]2026-05-06 15:40:31,313 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  30%|███       | 61/200 [02:08<04:53,  2.11s/it]2026-05-06 15:40:33,355 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  31%|███       | 62/200 [02:10<04:48,  2.09s/it]2026-05-06 15:40:35,670 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  32%|███▏      | 63/200 [02:13<04:55,  2.16s/it]2026-05-06 15:40:37,676 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  32%|███▏      | 64/200 [02:15<04:47,  2.11s/it]2026-05-06 15:40:39,830 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  32%|███▎      | 65/200 [02:17<04:46,  2.13s/it]2026-05-06 15:40:42,206 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  33%|███▎      | 66/200 [02:19<04:54,  2.20s/it]2026-05-06 15:40:44,333 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  34%|███▎      | 67/200 [02:21<04:49,  2.18s/it]2026-05-06 15:40:46,325 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  34%|███▍      | 68/200 [02:23<04:40,  2.12s/it]2026-05-06 15:40:48,748 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  34%|███▍      | 69/200 [02:26<04:49,  2.21s/it]2026-05-06 15:40:50,306 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  35%|███▌      | 70/200 [02:27<04:22,  2.02s/it]2026-05-06 15:40:52,026 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  36%|███▌      | 71/200 [02:29<04:08,  1.93s/it]2026-05-06 15:40:53,983 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  36%|███▌      | 72/200 [02:31<04:07,  1.94s/it]2026-05-06 15:40:56,282 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  36%|███▋      | 73/200 [02:33<04:19,  2.04s/it]2026-05-06 15:40:57,911 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  37%|███▋      | 74/200 [02:35<04:01,  1.92s/it]2026-05-06 15:40:59,986 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  38%|███▊      | 75/200 [02:37<04:05,  1.97s/it]2026-05-06 15:41:02,542 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  38%|███▊      | 76/200 [02:39<04:25,  2.14s/it]2026-05-06 15:41:04,238 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  38%|███▊      | 77/200 [02:41<04:07,  2.01s/it]2026-05-06 15:41:05,845 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  39%|███▉      | 78/200 [02:43<03:50,  1.89s/it]2026-05-06 15:41:07,986 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  40%|███▉      | 79/200 [02:45<03:57,  1.96s/it]2026-05-06 15:41:10,653 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  40%|████      | 80/200 [02:48<04:20,  2.17s/it]2026-05-06 15:41:13,275 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  40%|████      | 81/200 [02:50<04:34,  2.31s/it]2026-05-06 15:41:15,364 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  41%|████      | 82/200 [02:52<04:24,  2.24s/it]2026-05-06 15:41:17,443 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  42%|████▏     | 83/200 [02:54<04:16,  2.19s/it]2026-05-06 15:41:19,825 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  42%|████▏     | 84/200 [02:57<04:20,  2.25s/it]2026-05-06 15:41:21,512 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  42%|████▎     | 85/200 [02:58<03:59,  2.08s/it]2026-05-06 15:41:23,398 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  43%|████▎     | 86/200 [03:00<03:50,  2.02s/it]2026-05-06 15:41:24,920 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  44%|████▎     | 87/200 [03:02<03:31,  1.87s/it]2026-05-06 15:41:28,238 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  44%|████▍     | 88/200 [03:05<04:18,  2.31s/it]2026-05-06 15:41:30,178 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  44%|████▍     | 89/200 [03:07<04:03,  2.20s/it]2026-05-06 15:41:31,980 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  45%|████▌     | 90/200 [03:09<03:48,  2.08s/it]2026-05-06 15:41:33,556 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  46%|████▌     | 91/200 [03:10<03:30,  1.93s/it]2026-05-06 15:41:35,048 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  46%|████▌     | 92/200 [03:12<03:14,  1.80s/it]2026-05-06 15:41:36,914 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  46%|████▋     | 93/200 [03:14<03:14,  1.82s/it]2026-05-06 15:41:38,665 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  47%|████▋     | 94/200 [03:16<03:10,  1.80s/it]2026-05-06 15:41:40,270 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  48%|████▊     | 95/200 [03:17<03:02,  1.74s/it]2026-05-06 15:41:42,313 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  48%|████▊     | 96/200 [03:19<03:10,  1.83s/it]2026-05-06 15:41:44,369 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  48%|████▊     | 97/200 [03:21<03:15,  1.90s/it]2026-05-06 15:41:46,216 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  49%|████▉     | 98/200 [03:23<03:12,  1.88s/it]2026-05-06 15:41:47,690 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  50%|████▉     | 99/200 [03:25<02:57,  1.76s/it]2026-05-06 15:41:50,090 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  50%|█████     | 100/200 [03:27<03:15,  1.95s/it]2026-05-06 15:41:52,136 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  50%|█████     | 101/200 [03:29<03:16,  1.98s/it]2026-05-06 15:41:53,851 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  51%|█████     | 102/200 [03:31<03:06,  1.90s/it]2026-05-06 15:41:55,788 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  52%|█████▏    | 103/200 [03:33<03:05,  1.91s/it]2026-05-06 15:41:57,790 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  52%|█████▏    | 104/200 [03:35<03:06,  1.94s/it]2026-05-06 15:41:59,742 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  52%|█████▎    | 105/200 [03:37<03:04,  1.94s/it]2026-05-06 15:42:03,778 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  53%|█████▎    | 106/200 [03:41<04:01,  2.57s/it]2026-05-06 15:42:05,206 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  54%|█████▎    | 107/200 [03:42<03:27,  2.23s/it]2026-05-06 15:42:07,449 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  54%|█████▍    | 108/200 [03:44<03:25,  2.23s/it]2026-05-06 15:42:09,265 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  55%|█████▍    | 109/200 [03:46<03:11,  2.11s/it]2026-05-06 15:42:11,821 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  55%|█████▌    | 110/200 [03:49<03:21,  2.24s/it]2026-05-06 15:42:13,875 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  56%|█████▌    | 111/200 [03:51<03:14,  2.19s/it]2026-05-06 15:42:16,324 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  56%|█████▌    | 112/200 [03:53<03:19,  2.26s/it]2026-05-06 15:42:18,267 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  56%|█████▋    | 113/200 [03:55<03:08,  2.17s/it]2026-05-06 15:42:20,188 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

=== Résultats Zero-Shot ===
  mode                      : zero_shot
  model                     : llama3.1:8b
  n_samples                 : 200
  top_k                     : 3
  accuracy_at_k             : 0.7
  top1_accuracy             : 0.505
  mrr_at_k                  : 0.5849999999999997
  empty_predictions         : 0
  time_seconds              : 423.9
  seconds_per_article       : 2.12

---
## 7. Évaluation Few-Shot

---
## 7b. Évaluation Few-Shot Dynamique (TF-IDF)

Pour chaque article, on sélectionne les **N articles les plus similaires** dans le train set via similarité cosine TF-IDF. Ces exemples pertinents remplacent les exemples statiques du few-shot classique.

In [ ]:
df_results = pd.DataFrame([results_zs, results_fs, results_dfs])
df_results = df_results[['mode', 'model', 'n_samples', 'top_k', 'top1_accuracy',
                          'accuracy_at_k', 'mrr_at_k', 'empty_predictions',
                          'time_seconds', 'seconds_per_article']]
df_results

In [15]:
# Sélection d'exemples pour le few-shot : 1 par catégorie depuis le train (couverture complète)
few_shot_examples = []

for cat in CATEGORIES:
    cat_samples = training_data[training_data['category'] == cat]
    if len(cat_samples) > 0:
        sample = cat_samples.sample(1, random_state=42).iloc[0]
        few_shot_examples.append({
            "text": sample['text'][:200],  # Tronquer pour limiter la taille du prompt
            "category": cat
        })

print(f"{len(few_shot_examples)} exemples few-shot sélectionnés (1 par catégorie, couverture complète)")
print("\nAperçu (3 premiers) :")
for ex in few_shot_examples[:3]:
    print(f"  [{ex['category']}] {ex['text'][:80]}...")

30 exemples few-shot sélectionnés (1 par catégorie, couverture complète)

Aperçu (3 premiers) :
  [ARTS] Koons, Walker and the Examination of Life and Death. Jeff Koons and Kara Walker ...
  [ARTS & CULTURE] Artist Proposes A New Way Of Seeing Nude Women At The Museum. With a little help...
  [BLACK VOICES] MLK's Daughter Says We Must Remember Her Mother's Legacy, Too. “Without #Coretta...

In [ ]:
eval_data_analysis = eval_data.copy()
eval_data_analysis['preds_zero_shot'] = preds_zs
eval_data_analysis['preds_few_shot'] = preds_fs
eval_data_analysis['preds_dynamic'] = preds_dfs
eval_data_analysis['correct_zs'] = eval_data_analysis.apply(
    lambda r: r['category'] in r['preds_zero_shot'], axis=1
)
eval_data_analysis['correct_fs'] = eval_data_analysis.apply(
    lambda r: r['category'] in r['preds_few_shot'], axis=1
)
eval_data_analysis['correct_dfs'] = eval_data_analysis.apply(
    lambda r: r['category'] in r['preds_dynamic'], axis=1
)

# Accuracy par catégorie pour les 3 modes
cat_accuracy = eval_data_analysis.groupby('category')[['correct_zs', 'correct_fs', 'correct_dfs']].mean()
cat_accuracy.columns = ['zero_shot', 'few_shot', 'dynamic_few_shot']
cat_accuracy = cat_accuracy.sort_values('zero_shot', ascending=False)
print("Accuracy par catégorie (top-k) :")
print(cat_accuracy.to_string())

---
## 8. Comparaison des résultats

In [17]:
df_results = pd.DataFrame([results_zs, results_fs])
df_results = df_results[['mode', 'model', 'n_samples', 'top_k', 'top1_accuracy',
                          'accuracy_at_k', 'mrr_at_k', 'empty_predictions',
                          'time_seconds', 'seconds_per_article']]
df_results

,mode,model,n_samples,top_k,top1_accuracy,accuracy_at_k,mrr_at_k,empty_predictions,time_seconds,seconds_per_article
0,zero_shot,llama3.1:8b,200,3,0.505,0.700,0.585000,0,423.9,2.12
1,few_shot,llama3.1:8b,200,3,0.530,0.755,0.625833,0,379.0,1.89

### Analyse des erreurs

In [18]:
# Analyse détaillée des prédictions zero-shot
eval_data_analysis = eval_data.copy()
eval_data_analysis['preds_zero_shot'] = preds_zs
eval_data_analysis['preds_few_shot'] = preds_fs
eval_data_analysis['correct_zs'] = eval_data_analysis.apply(
    lambda r: r['category'] in r['preds_zero_shot'], axis=1
)
eval_data_analysis['correct_fs'] = eval_data_analysis.apply(
    lambda r: r['category'] in r['preds_few_shot'], axis=1
)

# Accuracy par catégorie (zero-shot)
cat_accuracy = eval_data_analysis.groupby('category')['correct_zs'].mean().sort_values(ascending=False)
print("Accuracy par catégorie (zero-shot, top-k) :")
print(cat_accuracy.to_string())

Accuracy par catégorie (zero-shot, top-k) :
category
ARTS              1.000000
ARTS & CULTURE    1.000000
GOOD NEWS         1.000000
SCIENCE           1.000000
SPORTS            1.000000
LATINO VOICES     1.000000
TASTE             1.000000
TECH              1.000000
WORLD NEWS        1.000000
POLITICS          0.909091
ENTERTAINMENT     0.909091
STYLE             0.800000
BUSINESS          0.750000
CRIME             0.750000
MEDIA             0.750000
HEALTHY LIVING    0.727273
QUEER VOICES      0.666667
RELIGION          0.600000
COLLEGE           0.500000
TRAVEL            0.500000
PARENTS           0.428571
COMEDY            0.400000
BLACK VOICES      0.333333
WEIRD NEWS        0.333333
IMPACT            0.333333
EDUCATION         0.000000
GREEN             0.000000
FIFTY             0.000000
WOMEN             0.000000
WORLDPOST         0.000000

In [19]:
# Exemples d'erreurs
errors = eval_data_analysis[~eval_data_analysis['correct_zs']].head(10)
print("Exemples d'erreurs (zero-shot) :\n")
for _, row in errors.iterrows():
    print(f"  Texte  : {row['text'][:120]}...")
    print(f"  Vrai   : {row['category']}")
    print(f"  Prédit : {row['preds_zero_shot']}")
    print()

Exemples d'erreurs (zero-shot) :

  Texte  : The Smartest Thing I've Ever Read About Consent. Cathy Young's recent piece in the Washington Post, "Feminists want us t...
  Vrai   : EDUCATION
  Prédit : ['WOMEN', 'ARTS & CULTURE', 'POLITICS']

  Texte  : A Carol for Our Times: The Melrose Quartet Perform 'Sing John Ball' (VIDEO). As a music journalist it may seem out of pl...
  Vrai   : RELIGION
  Prédit : ['ARTS & CULTURE', 'ENTERTAINMENT']

  Texte  : Frequencies: Law of Attraction. I've noticed that as soon as I allow myself to worry about something, it begins to take ...
  Vrai   : COLLEGE
  Prédit : ['HEALTHY LIVING', 'ARTS & CULTURE', 'GOOD NEWS']

  Texte  : John Oliver Calls Out The Academy For Hypocrisy After Weinstein Decision. The "Last Week Tonight" host takes on Hollywoo...
  Vrai   : COMEDY
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'POLITICS']

  Texte  : RuPaul Is Getting A Star On The Walk Of Fame. Shantay, you stay!. rupaul star walk of fame us 594d3a65e4b02734df2a0dba...
  Vrai   : QUEER VOICES
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'STYLE']

  Texte  : Ode to Football: A Sport I Kind of Can't Stand. I revere football because it provides an opportunity in pop culture to w...
  Vrai   : QUEER VOICES
  Prédit : ['ARTS', 'ENTERTAINMENT', 'SPORTS']

  Texte  : Social Equality: The Best Cure for Uterine Prolapse in Nepal. In November of 1987, I gave birth in the plains of Nepal. ...
  Vrai   : IMPACT
  Prédit : ['WORLD NEWS', 'HEALTHY LIVING', 'ARTS']

  Texte  : Two Police Officers Stabbed In Belgium In Possible Extremist Attack. Counter terror prosecutors have stepped in to inves...
  Vrai   : WORLDPOST
  Prédit : ['WORLD NEWS', 'CRIME', 'IMPACT']

  Texte  : Meet The 70-Year-Old Hiking The Pacific Crest Trail. My friend Tony and I just returned from meeting up with our friend ...
  Vrai   : FIFTY
  Prédit : ['TRAVEL', 'SPORTS', 'GOOD NEWS']

  Texte  : The 20 Funniest Tweets From Women This Week. The ladies of Twitter never fail to brighten our days with their brilliant ...
  Vrai   : WOMEN
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'COMEDY']

---
## 9. Prédictions sur articles CNN (non vus) — comme le notebook de référence

In [ ]:
output_path = r"C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\results\llm_evaluation_results.json"

import os
os.makedirs(os.path.dirname(output_path), exist_ok=True)

results_to_save = {
    "zero_shot": results_zs,
    "few_shot": results_fs,
    "dynamic_few_shot": results_dfs,
    "config": {
        "model": OLLAMA_MODEL,
        "eval_sample_size": EVAL_SAMPLE_SIZE,
        "top_k": TOP_K,
        "n_categories": len(CATEGORIES),
        "n_dynamic_examples": N_DYNAMIC_EXAMPLES,
    }
}

with open(output_path, 'w') as f:
    json.dump(results_to_save, f, indent=2)

print(f"Résultats sauvegardés dans {output_path}")

---
## 10. Bonus — Tester différents modèles Ollama

In [21]:
# Décommenter et adapter pour tester plusieurs modèles
# Assurez-vous d'avoir pull les modèles avec `ollama pull <model>`

MODELS_TO_TEST = [
    # "llama3.1:8b",
    # "mistral",
    # "gemma2:9b",
    # "phi3",
]

if MODELS_TO_TEST:
    # Sous-échantillon plus petit pour le benchmark multi-modèles
    benchmark_data = eval_data.sample(n=min(50, len(eval_data)), random_state=123).reset_index(drop=True)
    
    all_results = []
    for model_name in MODELS_TO_TEST:
        print(f"\n--- Test du modèle : {model_name} ---")
        try:
            res, _ = run_evaluation(
                eval_df=benchmark_data,
                categories=CATEGORIES,
                model=model_name,
                top_k=TOP_K,
                mode="zero_shot"
            )
            all_results.append(res)
            print(f"  Accuracy@{TOP_K}: {res['accuracy_at_k']:.3f} | MRR: {res['mrr_at_k']:.3f}")
        except Exception as e:
            print(f"  Erreur : {e}")
    
    if all_results:
        df_benchmark = pd.DataFrame(all_results)
        print("\n=== Comparaison des modèles ===")
        display(df_benchmark)
else:
    print("Ajoutez des modèles à MODELS_TO_TEST pour lancer le benchmark multi-modèles.")

Ajoutez des modèles à MODELS_TO_TEST pour lancer le benchmark multi-modèles.

---
## 11. Sauvegarde des résultats

In [22]:
# Sauvegarder les résultats d'évaluation
output_path = r"C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\results\llm_evaluation_results.json"

import os
os.makedirs(os.path.dirname(output_path), exist_ok=True)

results_to_save = {
    "zero_shot": results_zs,
    "few_shot": results_fs,
    "config": {
        "model": OLLAMA_MODEL,
        "eval_sample_size": EVAL_SAMPLE_SIZE,
        "top_k": TOP_K,
        "n_categories": len(CATEGORIES),
    }
}

with open(output_path, 'w') as f:
    json.dump(results_to_save, f, indent=2)

print(f"Résultats sauvegardés dans {output_path}")

Résultats sauvegardés dans C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\results\llm_evaluation_results.json

---
## Résumé

| Aspect | Notebook NLP (référence) | Notebook LLM (Ollama) |
|--------|--------------------------|------------------------|
| **Features** | TF-IDF / Binary / Counts | Texte brut envoyé au LLM |
| **Modèle** | Logistic Regression (sklearn) | LLM local (Ollama) |
| **Entraînement** | Nécessaire (fit sur train set) | Aucun (zero-shot) ou quelques exemples (few-shot) |
| **Vitesse** | Très rapide (~secondes) | Lent (~1-5s par article) |
| **Flexibilité** | Fixé aux catégories du train | Peut classifier vers de nouvelles catégories |
| **Évaluation** | Accuracy + MRR@k | Accuracy + MRR@k (identique) |