# News Category Prediction — Approche LLM avec Ollama

Ce notebook reprend le même dataset et les mêmes objectifs que le notebook de référence (classification d'articles HuffPost en catégories), mais remplace le pipeline NLP classique (TF-IDF + Logistic Regression) par une **prédiction via un LLM local** servi par **Ollama**.

### Approches testées
1. **Zero-shot** : on donne la liste des catégories et le texte, le LLM prédit.
2. **Few-shot** : on ajoute quelques exemples dans le prompt pour guider le modèle.
3. **Évaluation** : Accuracy et MRR@k, identiques au notebook de référence.

### Prérequis
- [Ollama](https://ollama.ai) installé et lancé (`ollama serve`)
- Un modèle téléchargé, par ex. `ollama pull llama3.1:8b` ou `mistral`

---
## 1. Installation & Imports

In [17]:
import pandas as pd
import numpy as np
import json
import re
import time
import logging
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import ollama

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

---
## 2. Configuration Ollama

In [18]:
# ---- Configuration ----
OLLAMA_MODEL = "llama3.1:8b"
EVAL_SAMPLE_SIZE = 200
TOP_K = 3
N_DYNAMIC_EXAMPLES = 5  # Nombre d'exemples TF-IDF pour le few-shot dynamique

# Vérifier que Ollama est joignable
try:
    response = ollama.list()
    print("Ollama est connecté. Modèles disponibles :")
    print(type(response))
    print(response)
except Exception as e:
    print(f"Erreur de connexion à Ollama : {e}")

2026-05-11 11:03:20,590 : INFO : HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"

Ollama est connecté. Modèles disponibles :
<class 'ollama._types.ListResponse'>
models=[Model(model='llama3.1:8b', modified_at=datetime.datetime(2026, 4, 14, 22, 26, 0, 102035, tzinfo=TzInfo(7200)), digest='46e0c10c039e019119339687c3c1757cc81b9da49709a3b3924863ba87ca666e', size=4920753328, details=ModelDetails(parent_model='', format='gguf', family='llama', families=['llama'], parameter_size='8.0B', quantization_level='Q4_K_M'))]

---
## 3. Chargement des données

In [19]:
df = pd.read_json(r"C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\data\news_category_dataset.json", lines=True)
print(f"Nombre d'articles : {len(df)}")
print(f"Colonnes : {list(df.columns)}")
df.head(3)

Nombre d'articles : 124989
Colonnes : ['short_description', 'headline', 'date', 'link', 'authors', 'category']

,short_description,headline,date,link,authors,category
0,She left her husband. He killed their children...,There Were 2 Mass Shootings In Texas Last Week...,2018-05-26,https://www.huffingtonpost.com/entry/texas-ama...,Melissa Jeltsen,CRIME
1,Of course it has a song.,Will Smith Joins Diplo And Nicky Jam For The 2...,2018-05-26,https://www.huffingtonpost.com/entry/will-smit...,Andy McDonald,ENTERTAINMENT
2,The actor and his longtime girlfriend Anna Ebe...,Hugh Grant Marries For The First Time At Age 57,2018-05-26,https://www.huffingtonpost.com/entry/hugh-gran...,Ron Dicker,ENTERTAINMENT

In [20]:
# Liste des catégories du dataset
CATEGORIES = sorted(df['category'].unique().tolist())
print(f"Nombre de catégories : {len(CATEGORIES)}")
print(CATEGORIES)

# Fusion WORLDPOST / THE WORLDPOST (catégories identiques dans HuffPost)
df['category'] = df['category'].replace({'THE WORLDPOST': 'WORLDPOST'})
CATEGORIES = sorted(df['category'].unique().tolist())
print(f"\nAprès fusion WORLDPOST : {len(CATEGORIES)} catégories")
print(CATEGORIES)

Nombre de catégories : 31
['ARTS', 'ARTS & CULTURE', 'BLACK VOICES', 'BUSINESS', 'COLLEGE', 'COMEDY', 'CRIME', 'EDUCATION', 'ENTERTAINMENT', 'FIFTY', 'GOOD NEWS', 'GREEN', 'HEALTHY LIVING', 'IMPACT', 'LATINO VOICES', 'MEDIA', 'PARENTS', 'POLITICS', 'QUEER VOICES', 'RELIGION', 'SCIENCE', 'SPORTS', 'STYLE', 'TASTE', 'TECH', 'THE WORLDPOST', 'TRAVEL', 'WEIRD NEWS', 'WOMEN', 'WORLD NEWS', 'WORLDPOST']

Après fusion WORLDPOST : 30 catégories
['ARTS', 'ARTS & CULTURE', 'BLACK VOICES', 'BUSINESS', 'COLLEGE', 'COMEDY', 'CRIME', 'EDUCATION', 'ENTERTAINMENT', 'FIFTY', 'GOOD NEWS', 'GREEN', 'HEALTHY LIVING', 'IMPACT', 'LATINO VOICES', 'MEDIA', 'PARENTS', 'POLITICS', 'QUEER VOICES', 'RELIGION', 'SCIENCE', 'SPORTS', 'STYLE', 'TASTE', 'TECH', 'TRAVEL', 'WEIRD NEWS', 'WOMEN', 'WORLD NEWS', 'WORLDPOST']

### Préparation du texte (identique au notebook de référence)

In [21]:
def tokenize_url(url: str):
    url = url.replace("https://www.huffingtonpost.com/entry/", "")
    url = re.sub(r"(\W|_)+", " ", url)
    return url

df['tokenized_url'] = df['link'].apply(tokenize_url)

# Texte combiné : description + headline
df['text'] = df['headline'] + '. ' + df['short_description']
df['text'] = df['text'].fillna('')

df[['category', 'headline', 'short_description', 'text']].sample(5)

,category,headline,short_description,text
41034,CRIME,Suspect In Custody After Robbery Turns To Host...,At least 11 people were held hostage.,Suspect In Custody After Robbery Turns To Host...
92128,CRIME,Officers Injured As Seattle Protests Turn Violent,,Officers Injured As Seattle Protests Turn Viol...
97029,SCIENCE,Is a Self-Aware Robot Like Chappie Possible?,I was fortunate enough to be invited to a scre...,Is a Self-Aware Robot Like Chappie Possible?. ...
116954,BUSINESS,10 Cities Where Wages Are Soaring,,10 Cities Where Wages Are Soaring.
13061,ENTERTAINMENT,Eleven's New Psychic Ally Just Changed The Gam...,"Eleven and Eight, together again.",Eleven's New Psychic Ally Just Changed The Gam...

### Split train / test

In [22]:
training_data, testing_data = train_test_split(df, random_state=2000)
print(f"Train : {len(training_data)} | Test : {len(testing_data)}")

# Sous-échantillonnage du test pour l'évaluation LLM (coût en temps)
eval_data = testing_data.sample(n=min(EVAL_SAMPLE_SIZE, len(testing_data)), random_state=42).reset_index(drop=True)
print(f"Échantillon d'évaluation : {len(eval_data)} articles")

Train : 93741 | Test : 31248
Échantillon d'évaluation : 200 articles

In [23]:
# ---- Index TF-IDF pour le few-shot dynamique ----
logging.info("Construction de l'index TF-IDF sur le train set...")
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, max_features=50_000)
train_vectors = tfidf_vectorizer.fit_transform(training_data['text'].values)
training_data_reset = training_data.reset_index(drop=True)
logging.info(f"Index TF-IDF : {train_vectors.shape[0]} docs, {train_vectors.shape[1]} features.")


def get_dynamic_examples(article_text: str, n_examples: int = N_DYNAMIC_EXAMPLES) -> list:
    """Sélectionne les N articles les plus similaires via similarité cosine TF-IDF."""
    article_vec = tfidf_vectorizer.transform([article_text])
    sims = cosine_similarity(article_vec, train_vectors)[0]
    top_indices = sims.argsort()[-n_examples:][::-1]
    return [
        {
            "text": training_data_reset.iloc[i]['text'][:200],
            "category": training_data_reset.iloc[i]['category']
        }
        for i in top_indices
    ]


# Démonstration sur le premier article d'évaluation
test_article = eval_data.iloc[0]['text']
print(f"Article : {test_article[:100]}...\n")
print(f"Top-{N_DYNAMIC_EXAMPLES} exemples dynamiques :")
for ex in get_dynamic_examples(test_article):
    print(f"  [{ex['category']}] {ex['text'][:80]}...")

2026-05-11 11:03:22,366 : INFO : Construction de l'index TF-IDF sur le train set...
2026-05-11 11:03:24,292 : INFO : Index TF-IDF : 93741 docs, 34187 features.

Article : Trump Admin Plans To Impose 20 Percent Duties On Canadian Softwood Lumber. The move escalates a long...

Top-5 exemples dynamiques :
  [POLITICS] Trump Says He Will 'Renegotiate' NAFTA. Trump previously accused Mexico of destr...
  [POLITICS] Trump Administration Orders Russia To Close Several Diplomatic Facilities In U.S...
  [POLITICS] Canada And The U.S. Face Off As Trade War Heats Up. The battle over softwood lum...
  [POLITICS] Donald Trump Threatens 35 Percent Tariff As 'Retribution' For Companies That Mov...
  [POLITICS] The One Percent. ...

---
## 4. Fonctions de prédiction via Ollama

In [24]:
def build_zero_shot_prompt(text: str, categories: list, top_k: int = 3) -> str:
    """Construit un prompt zero-shot pour la classification."""
    cats_str = ", ".join(categories)
    prompt = f"""You are a news article classifier. Your task is to assign the most appropriate category to a news article.

CATEGORIES:
{cats_str}

ARTICLE:
\"\"\"
{text}
\"\"\"

Return EXACTLY {top_k} categories from the list above, ranked from most likely to least likely.
Respond ONLY with a JSON array of strings, nothing else. Example: ["POLITICS", "BUSINESS", "CRIME"]
"""
    return prompt


def build_few_shot_prompt(text: str, categories: list, examples: list, top_k: int = 3) -> str:
    """Construit un prompt few-shot avec des exemples."""
    cats_str = ", ".join(categories)
    
    examples_str = ""
    for ex in examples:
        examples_str += f'Article: "{ex["text"]}"\nCategory: {ex["category"]}\n\n'
    
    prompt = f"""You are a news article classifier. Your task is to assign the most appropriate category to a news article.

CATEGORIES:
{cats_str}

Here are some examples:

{examples_str}
Now classify this article:

ARTICLE:
\"\"\"
{text}
\"\"\"

Return EXACTLY {top_k} categories from the list above, ranked from most likely to least likely.
Respond ONLY with a JSON array of strings, nothing else. Example: ["POLITICS", "BUSINESS", "CRIME"]
"""
    return prompt


print("Exemple de prompt zero-shot :")
print(build_zero_shot_prompt("Biden announces new climate policy for 2025", CATEGORIES[:5], top_k=3))

Exemple de prompt zero-shot :
You are a news article classifier. Your task is to assign the most appropriate category to a news article.

CATEGORIES:
ARTS, ARTS & CULTURE, BLACK VOICES, BUSINESS, COLLEGE

ARTICLE:
"""
Biden announces new climate policy for 2025
"""

Return EXACTLY 3 categories from the list above, ranked from most likely to least likely.
Respond ONLY with a JSON array of strings, nothing else. Example: ["POLITICS", "BUSINESS", "CRIME"]

In [25]:
def parse_llm_response(response_text: str, valid_categories: list, top_k: int = 3) -> list:
    """
    Parse la réponse du LLM pour en extraire les catégories prédites.
    Gère les formats variés que le LLM peut retourner.
    """
    text = response_text.strip()
    
    # Tenter le parsing JSON direct
    try:
        # Extraire le JSON s'il est entouré de texte
        json_match = re.search(r'\[.*?\]', text, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group())
            # Normaliser en majuscules et filtrer les catégories valides
            preds = [p.strip().upper() for p in parsed if isinstance(p, str)]
            preds = [p for p in preds if p in valid_categories]
            if preds:
                return preds[:top_k]
    except (json.JSONDecodeError, AttributeError):
        pass
    
    # Fallback : chercher les catégories mentionnées dans le texte
    text_upper = text.upper()
    found = [cat for cat in valid_categories if cat in text_upper]
    if found:
        return found[:top_k]
    
    # Dernier recours : retourner une liste vide
    return []


# Test du parser
test_responses = [
    '["POLITICS", "CRIME", "BUSINESS"]',
    'The article is about POLITICS and CRIME.',
    'Here are my predictions:\n["ENTERTAINMENT", "COMEDY"]',
]
for resp in test_responses:
    print(f"  Input:  {resp!r}")
    print(f"  Parsed: {parse_llm_response(resp, CATEGORIES)}")
    print()

  Input:  '["POLITICS", "CRIME", "BUSINESS"]'
  Parsed: ['POLITICS', 'CRIME', 'BUSINESS']

  Input:  'The article is about POLITICS and CRIME.'
  Parsed: ['CRIME', 'POLITICS']

  Input:  'Here are my predictions:\n["ENTERTAINMENT", "COMEDY"]'
  Parsed: ['ENTERTAINMENT', 'COMEDY']

In [26]:
def predict_with_ollama(text: str, categories: list, model: str = OLLAMA_MODEL,
                         top_k: int = 3, mode: str = "zero_shot",
                         examples: list = None, n_dynamic: int = N_DYNAMIC_EXAMPLES) -> list:
    """
    Appelle Ollama pour prédire les catégories d'un texte.

    mode : 'zero_shot' | 'few_shot' | 'dynamic_few_shot'
    """
    if mode == "dynamic_few_shot":
        dynamic_examples = get_dynamic_examples(text, n_examples=n_dynamic)
        prompt = build_few_shot_prompt(text, categories, dynamic_examples, top_k)
    elif mode == "few_shot" and examples:
        prompt = build_few_shot_prompt(text, categories, examples, top_k)
    else:
        prompt = build_zero_shot_prompt(text, categories, top_k)

    try:
        response = ollama.chat(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            options={
                "temperature": 0.1,
                "num_predict": 100,
            }
        )
        response_text = response['message']['content']
        return parse_llm_response(response_text, categories, top_k)
    except Exception as e:
        logging.error(f"Erreur Ollama : {e}")
        return []

### Test rapide sur un article

In [27]:
# Test sur un article du dataset
sample = eval_data.iloc[0]
print(f"Texte  : {sample['text'][:200]}...")
print(f"Vrai   : {sample['category']}")

pred = predict_with_ollama(sample['text'], CATEGORIES, top_k=TOP_K)
print(f"Prédit : {pred}")

Texte  : Trump Admin Plans To Impose 20 Percent Duties On Canadian Softwood Lumber. The move escalates a long-running trade dispute between the two countries....
Vrai   : POLITICS

2026-05-11 11:03:35,469 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Prédit : ['POLITICS', 'BUSINESS', 'WORLD NEWS']

---
## 5. Fonctions d'évaluation (reprises du notebook de référence)

In [28]:
def _reciprocal_rank(true_labels: list, machine_preds: list):
    """Compute the reciprocal rank at cutoff k"""
    tp_pos_list = [(idx + 1) for idx, r in enumerate(machine_preds) if r in true_labels]
    rr = 0
    if len(tp_pos_list) > 0:
        first_pos_list = tp_pos_list[0]
        rr = 1 / float(first_pos_list)
    return rr


def compute_mrr_at_k(items: list):
    """Compute the MRR (average RR) at cutoff k"""
    rr_total = 0
    for item in items:
        rr_at_k = _reciprocal_rank(item[0], item[1])
        rr_total += rr_at_k
    mrr = rr_total / float(len(items))
    return mrr


def compute_accuracy(eval_items: list):
    """Accuracy : le vrai label est-il dans les top-k prédictions ?"""
    correct = 0
    for item in eval_items:
        true_pred = item[0]
        machine_pred = set(item[1])
        for cat in true_pred:
            if cat in machine_pred:
                correct += 1
                break
    accuracy = correct / float(len(eval_items))
    return accuracy


def collect_preds(y_true: list, y_preds: list):
    return [[[y_true[idx]], pred] for idx, pred in enumerate(y_preds)]

---
## 6. Évaluation Zero-Shot

In [29]:
def run_evaluation(eval_df: pd.DataFrame, categories: list, model: str = OLLAMA_MODEL,
                   top_k: int = 3, mode: str = "zero_shot", examples: list = None,
                   n_dynamic: int = N_DYNAMIC_EXAMPLES):
    """Lance la prédiction LLM sur un DataFrame et calcule les métriques."""
    all_preds = []
    y_true = eval_df['category'].values.tolist()

    start_time = time.time()

    for idx, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc=f"Prédiction ({mode})"):
        preds = predict_with_ollama(
            text=row['text'],
            categories=categories,
            model=model,
            top_k=top_k,
            mode=mode,
            examples=examples,
            n_dynamic=n_dynamic
        )
        all_preds.append(preds)

    elapsed = time.time() - start_time

    eval_items = collect_preds(y_true, all_preds)
    accuracy = compute_accuracy(eval_items)
    mrr = compute_mrr_at_k(eval_items)

    top1_correct = sum(1 for true, pred in zip(y_true, all_preds) if pred and pred[0] == true)
    top1_acc = top1_correct / len(y_true)
    empty_preds = sum(1 for p in all_preds if len(p) == 0)

    results = {
        "mode": mode,
        "model": model,
        "n_samples": len(eval_df),
        "top_k": top_k,
        "accuracy_at_k": accuracy,
        "top1_accuracy": top1_acc,
        "mrr_at_k": mrr,
        "empty_predictions": empty_preds,
        "time_seconds": round(elapsed, 1),
        "seconds_per_article": round(elapsed / len(eval_df), 2),
    }

    return results, all_preds


print("Fonction d'évaluation prête.")

Fonction d'évaluation prête.

In [30]:
# ---- Évaluation Zero-Shot ----
logging.info(f"Lancement évaluation zero-shot sur {len(eval_data)} articles...")

results_zs, preds_zs = run_evaluation(
    eval_df=eval_data,
    categories=CATEGORIES,
    model=OLLAMA_MODEL,
    top_k=TOP_K,
    mode="zero_shot"
)

print("\n=== Résultats Zero-Shot ===")
for k, v in results_zs.items():
    print(f"  {k:25s} : {v}")

2026-05-11 11:03:35,513 : INFO : Lancement évaluation zero-shot sur 200 articles...
Prédiction (zero_shot):   0%|          | 0/200 [00:00<?, ?it/s]2026-05-11 11:03:36,904 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   0%|          | 1/200 [00:01<04:36,  1.39s/it]2026-05-11 11:03:38,483 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   1%|          | 2/200 [00:02<04:57,  1.50s/it]2026-05-11 11:03:40,789 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   2%|▏         | 3/200 [00:05<06:08,  1.87s/it]2026-05-11 11:03:43,108 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   2%|▏         | 4/200 [00:07<06:41,  2.05s/it]2026-05-11 11:03:45,264 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   2%|▎         | 5/200 [00:09<06:46,  2.09s/it]2026-05-11 11:03:47,063 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   3%|▎         | 6/200 [00:11<06:25,  1.99s/it]2026-05-11 11:03:48,469 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   4%|▎         | 7/200 [00:12<05:47,  1.80s/it]2026-05-11 11:03:49,923 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   4%|▍         | 8/200 [00:14<05:24,  1.69s/it]2026-05-11 11:03:51,865 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   4%|▍         | 9/200 [00:16<05:37,  1.77s/it]2026-05-11 11:03:54,282 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   5%|▌         | 10/200 [00:18<06:13,  1.97s/it]2026-05-11 11:03:56,275 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   6%|▌         | 11/200 [00:20<06:13,  1.98s/it]2026-05-11 11:03:57,767 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   6%|▌         | 12/200 [00:22<05:43,  1.83s/it]2026-05-11 11:03:59,738 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   6%|▋         | 13/200 [00:24<05:50,  1.87s/it]2026-05-11 11:04:02,257 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   7%|▋         | 14/200 [00:26<06:24,  2.07s/it]2026-05-11 11:04:03,912 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   8%|▊         | 15/200 [00:28<05:59,  1.94s/it]2026-05-11 11:04:05,974 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   8%|▊         | 16/200 [00:30<06:04,  1.98s/it]2026-05-11 11:04:08,447 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   8%|▊         | 17/200 [00:32<06:29,  2.13s/it]2026-05-11 11:04:09,967 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):   9%|▉         | 18/200 [00:34<05:53,  1.94s/it]2026-05-11 11:04:11,595 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  10%|▉         | 19/200 [00:36<05:34,  1.85s/it]2026-05-11 11:04:13,233 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  10%|█         | 20/200 [00:37<05:21,  1.79s/it]2026-05-11 11:04:15,075 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  10%|█         | 21/200 [00:39<05:22,  1.80s/it]2026-05-11 11:04:16,699 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  11%|█         | 22/200 [00:41<05:11,  1.75s/it]2026-05-11 11:04:18,324 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  12%|█▏        | 23/200 [00:42<05:03,  1.71s/it]2026-05-11 11:04:20,338 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  12%|█▏        | 24/200 [00:44<05:17,  1.80s/it]2026-05-11 11:04:21,725 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  12%|█▎        | 25/200 [00:46<04:53,  1.68s/it]2026-05-11 11:04:23,508 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  13%|█▎        | 26/200 [00:47<04:57,  1.71s/it]2026-05-11 11:04:24,922 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  14%|█▎        | 27/200 [00:49<04:40,  1.62s/it]2026-05-11 11:04:26,471 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  14%|█▍        | 28/200 [00:50<04:35,  1.60s/it]2026-05-11 11:04:28,572 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  14%|█▍        | 29/200 [00:53<04:59,  1.75s/it]2026-05-11 11:04:30,359 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  15%|█▌        | 30/200 [00:54<04:59,  1.76s/it]2026-05-11 11:04:31,993 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  16%|█▌        | 31/200 [00:56<04:51,  1.72s/it]2026-05-11 11:04:33,798 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  16%|█▌        | 32/200 [00:58<04:53,  1.75s/it]2026-05-11 11:04:35,563 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  16%|█▋        | 33/200 [01:00<04:52,  1.75s/it]2026-05-11 11:04:37,244 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  17%|█▋        | 34/200 [01:01<04:47,  1.73s/it]2026-05-11 11:04:39,012 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  18%|█▊        | 35/200 [01:03<04:47,  1.74s/it]2026-05-11 11:04:40,945 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  18%|█▊        | 36/200 [01:05<04:55,  1.80s/it]2026-05-11 11:04:42,413 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  18%|█▊        | 37/200 [01:06<04:37,  1.70s/it]2026-05-11 11:04:43,792 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  19%|█▉        | 38/200 [01:08<04:19,  1.60s/it]2026-05-11 11:04:45,740 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  20%|█▉        | 39/200 [01:10<04:34,  1.71s/it]2026-05-11 11:04:47,688 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  20%|██        | 40/200 [01:12<04:44,  1.78s/it]2026-05-11 11:04:49,524 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  20%|██        | 41/200 [01:14<04:45,  1.80s/it]2026-05-11 11:04:51,071 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  21%|██        | 42/200 [01:15<04:31,  1.72s/it]2026-05-11 11:04:53,434 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  22%|██▏       | 43/200 [01:17<05:00,  1.91s/it]2026-05-11 11:04:54,853 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  22%|██▏       | 44/200 [01:19<04:35,  1.77s/it]2026-05-11 11:04:56,238 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  22%|██▎       | 45/200 [01:20<04:15,  1.65s/it]2026-05-11 11:04:58,291 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  23%|██▎       | 46/200 [01:22<04:32,  1.77s/it]2026-05-11 11:04:59,993 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  24%|██▎       | 47/200 [01:24<04:27,  1.75s/it]2026-05-11 11:05:01,422 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  24%|██▍       | 48/200 [01:25<04:11,  1.65s/it]2026-05-11 11:05:03,431 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  24%|██▍       | 49/200 [01:27<04:25,  1.76s/it]2026-05-11 11:05:04,811 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  25%|██▌       | 50/200 [01:29<04:06,  1.65s/it]2026-05-11 11:05:06,124 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  26%|██▌       | 51/200 [01:30<03:50,  1.55s/it]2026-05-11 11:05:07,639 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  26%|██▌       | 52/200 [01:32<03:47,  1.54s/it]2026-05-11 11:05:09,490 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  26%|██▋       | 53/200 [01:33<03:59,  1.63s/it]2026-05-11 11:05:11,112 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  27%|██▋       | 54/200 [01:35<03:57,  1.63s/it]2026-05-11 11:05:13,272 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  28%|██▊       | 55/200 [01:37<04:19,  1.79s/it]2026-05-11 11:05:15,110 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  28%|██▊       | 56/200 [01:39<04:19,  1.80s/it]2026-05-11 11:05:16,754 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  28%|██▊       | 57/200 [01:41<04:10,  1.76s/it]2026-05-11 11:05:18,079 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  29%|██▉       | 58/200 [01:42<03:50,  1.63s/it]2026-05-11 11:05:20,252 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  30%|██▉       | 59/200 [01:44<04:12,  1.79s/it]2026-05-11 11:05:21,955 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  30%|███       | 60/200 [01:46<04:06,  1.76s/it]2026-05-11 11:05:23,663 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  30%|███       | 61/200 [01:48<04:02,  1.75s/it]2026-05-11 11:05:25,290 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  31%|███       | 62/200 [01:49<03:56,  1.71s/it]2026-05-11 11:05:27,460 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  32%|███▏      | 63/200 [01:51<04:13,  1.85s/it]2026-05-11 11:05:29,305 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  32%|███▏      | 64/200 [01:53<04:11,  1.85s/it]2026-05-11 11:05:30,857 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  32%|███▎      | 65/200 [01:55<03:57,  1.76s/it]2026-05-11 11:05:33,018 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  33%|███▎      | 66/200 [01:57<04:11,  1.88s/it]2026-05-11 11:05:34,977 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  34%|███▎      | 67/200 [01:59<04:13,  1.90s/it]2026-05-11 11:05:36,729 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  34%|███▍      | 68/200 [02:01<04:05,  1.86s/it]2026-05-11 11:05:38,520 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  34%|███▍      | 69/200 [02:03<04:00,  1.84s/it]2026-05-11 11:05:40,375 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  35%|███▌      | 70/200 [02:04<03:59,  1.84s/it]2026-05-11 11:05:42,135 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  36%|███▌      | 71/200 [02:06<03:54,  1.82s/it]2026-05-11 11:05:43,847 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  36%|███▌      | 72/200 [02:08<03:48,  1.79s/it]2026-05-11 11:05:45,257 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  36%|███▋      | 73/200 [02:09<03:32,  1.67s/it]2026-05-11 11:05:46,641 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  37%|███▋      | 74/200 [02:11<03:19,  1.59s/it]2026-05-11 11:05:48,743 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  38%|███▊      | 75/200 [02:13<03:37,  1.74s/it]2026-05-11 11:05:50,957 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  38%|███▊      | 76/200 [02:15<03:53,  1.88s/it]2026-05-11 11:05:52,803 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  38%|███▊      | 77/200 [02:17<03:50,  1.87s/it]2026-05-11 11:05:54,610 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  39%|███▉      | 78/200 [02:19<03:46,  1.85s/it]2026-05-11 11:05:56,388 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  40%|███▉      | 79/200 [02:20<03:41,  1.83s/it]2026-05-11 11:05:57,773 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  40%|████      | 80/200 [02:22<03:23,  1.70s/it]2026-05-11 11:05:59,956 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  40%|████      | 81/200 [02:24<03:39,  1.84s/it]2026-05-11 11:06:01,790 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  41%|████      | 82/200 [02:26<03:37,  1.84s/it]2026-05-11 11:06:03,097 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  42%|████▏     | 83/200 [02:27<03:16,  1.68s/it]2026-05-11 11:06:05,187 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  42%|████▏     | 84/200 [02:29<03:29,  1.80s/it]2026-05-11 11:06:06,997 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  42%|████▎     | 85/200 [02:31<03:27,  1.81s/it]2026-05-11 11:06:08,388 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  43%|████▎     | 86/200 [02:32<03:11,  1.68s/it]2026-05-11 11:06:09,776 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  44%|████▎     | 87/200 [02:34<02:59,  1.59s/it]2026-05-11 11:06:11,762 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  44%|████▍     | 88/200 [02:36<03:11,  1.71s/it]2026-05-11 11:06:13,420 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  44%|████▍     | 89/200 [02:37<03:08,  1.69s/it]2026-05-11 11:06:15,136 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  45%|████▌     | 90/200 [02:39<03:07,  1.70s/it]2026-05-11 11:06:17,198 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  46%|████▌     | 91/200 [02:41<03:17,  1.81s/it]2026-05-11 11:06:18,558 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  46%|████▌     | 92/200 [02:43<03:00,  1.67s/it]2026-05-11 11:06:20,268 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  46%|████▋     | 93/200 [02:44<03:00,  1.69s/it]2026-05-11 11:06:21,494 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  47%|████▋     | 94/200 [02:45<02:44,  1.55s/it]2026-05-11 11:06:22,865 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  48%|████▊     | 95/200 [02:47<02:36,  1.49s/it]2026-05-11 11:06:24,243 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  48%|████▊     | 96/200 [02:48<02:31,  1.46s/it]2026-05-11 11:06:26,360 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  48%|████▊     | 97/200 [02:50<02:50,  1.66s/it]2026-05-11 11:06:28,013 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  49%|████▉     | 98/200 [02:52<02:48,  1.66s/it]2026-05-11 11:06:29,792 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  50%|████▉     | 99/200 [02:54<02:50,  1.69s/it]2026-05-11 11:06:31,402 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  50%|█████     | 100/200 [02:55<02:46,  1.67s/it]2026-05-11 11:06:33,096 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  50%|█████     | 101/200 [02:57<02:45,  1.68s/it]2026-05-11 11:06:34,553 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  51%|█████     | 102/200 [02:59<02:37,  1.61s/it]2026-05-11 11:06:35,941 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  52%|█████▏    | 103/200 [03:00<02:29,  1.54s/it]2026-05-11 11:06:37,326 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  52%|█████▏    | 104/200 [03:01<02:23,  1.50s/it]2026-05-11 11:06:38,634 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  52%|█████▎    | 105/200 [03:03<02:16,  1.44s/it]2026-05-11 11:06:40,586 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  53%|█████▎    | 106/200 [03:05<02:29,  1.59s/it]2026-05-11 11:06:41,805 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  54%|█████▎    | 107/200 [03:06<02:17,  1.48s/it]2026-05-11 11:06:43,583 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  54%|█████▍    | 108/200 [03:08<02:24,  1.57s/it]2026-05-11 11:06:45,130 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  55%|█████▍    | 109/200 [03:09<02:22,  1.56s/it]2026-05-11 11:06:46,916 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  55%|█████▌    | 110/200 [03:11<02:26,  1.63s/it]2026-05-11 11:06:48,681 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  56%|█████▌    | 111/200 [03:13<02:28,  1.67s/it]2026-05-11 11:06:50,878 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  56%|█████▌    | 112/200 [03:15<02:40,  1.83s/it]2026-05-11 11:06:52,729 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (zero_shot):  56%|█████▋    | 113/200 [03:17<02:39,  1.84s/it]2026-05-11 11:06:54,516 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

=== Résultats Zero-Shot ===
  mode                      : zero_shot
  model                     : llama3.1:8b
  n_samples                 : 200
  top_k                     : 3
  accuracy_at_k             : 0.72
  top1_accuracy             : 0.51
  mrr_at_k                  : 0.5958333333333331
  empty_predictions         : 0
  time_seconds              : 353.1
  seconds_per_article       : 1.77

---
## 7. Évaluation Few-Shot

In [31]:
# Sélection d'exemples pour le few-shot (1 par catégorie, depuis le train)
# On prend un échantillon stratifié pour couvrir un maximum de catégories
few_shot_examples = []

for cat in CATEGORIES:
    cat_samples = training_data[training_data['category'] == cat]
    if len(cat_samples) > 0:
        sample = cat_samples.sample(1, random_state=42).iloc[0]
        few_shot_examples.append({
            "text": sample['text'][:200],  # Tronquer pour limiter la taille du prompt
            "category": cat
        })

print(f"{len(few_shot_examples)} exemples few-shot sélectionnés")
print("\nAperçu (3 premiers) :")
for ex in few_shot_examples[:3]:
    print(f"  [{ex['category']}] {ex['text'][:80]}...")

30 exemples few-shot sélectionnés

Aperçu (3 premiers) :
  [ARTS] Koons, Walker and the Examination of Life and Death. Jeff Koons and Kara Walker ...
  [ARTS & CULTURE] Artist Proposes A New Way Of Seeing Nude Women At The Museum. With a little help...
  [BLACK VOICES] MLK's Daughter Says We Must Remember Her Mother's Legacy, Too. “Without #Coretta...

In [32]:
# ---- Évaluation Few-Shot ----
# 1 exemple par catégorie = couverture complète des 30 catégories
logging.info(f"Lancement évaluation few-shot ({len(few_shot_examples)} exemples) sur {len(eval_data)} articles...")

results_fs, preds_fs = run_evaluation(
    eval_df=eval_data,
    categories=CATEGORIES,
    model=OLLAMA_MODEL,
    top_k=TOP_K,
    mode="few_shot",
    examples=few_shot_examples
)

print("\n=== Résultats Few-Shot ===")
for k, v in results_fs.items():
    print(f"  {k:25s} : {v}")

2026-05-11 11:09:28,810 : INFO : Lancement évaluation few-shot (30 exemples) sur 200 articles...
Prédiction (few_shot):   0%|          | 0/200 [00:00<?, ?it/s]2026-05-11 11:09:31,304 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   0%|          | 1/200 [00:02<08:15,  2.49s/it]2026-05-11 11:09:32,886 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   1%|          | 2/200 [00:04<06:27,  1.96s/it]2026-05-11 11:09:34,829 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   2%|▏         | 3/200 [00:06<06:24,  1.95s/it]2026-05-11 11:09:36,308 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   2%|▏         | 4/200 [00:07<05:45,  1.76s/it]2026-05-11 11:09:38,081 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   2%|▎         | 5/200 [00:09<05:44,  1.77s/it]2026-05-11 11:09:39,686 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   3%|▎         | 6/200 [00:10<05:32,  1.71s/it]2026-05-11 11:09:41,160 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   4%|▎         | 7/200 [00:12<05:15,  1.63s/it]2026-05-11 11:09:42,631 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   4%|▍         | 8/200 [00:13<05:03,  1.58s/it]2026-05-11 11:09:44,580 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   4%|▍         | 9/200 [00:15<05:24,  1.70s/it]2026-05-11 11:09:46,616 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   5%|▌         | 10/200 [00:17<05:42,  1.80s/it]2026-05-11 11:09:48,450 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   6%|▌         | 11/200 [00:19<05:42,  1.81s/it]2026-05-11 11:09:49,777 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   6%|▌         | 12/200 [00:20<05:12,  1.66s/it]2026-05-11 11:09:51,342 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   6%|▋         | 13/200 [00:22<05:05,  1.63s/it]2026-05-11 11:09:53,250 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   7%|▋         | 14/200 [00:24<05:19,  1.72s/it]2026-05-11 11:09:54,756 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   8%|▊         | 15/200 [00:25<05:05,  1.65s/it]2026-05-11 11:09:56,225 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   8%|▊         | 16/200 [00:27<04:54,  1.60s/it]2026-05-11 11:09:57,702 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   8%|▊         | 17/200 [00:28<04:45,  1.56s/it]2026-05-11 11:09:59,167 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):   9%|▉         | 18/200 [00:30<04:38,  1.53s/it]2026-05-11 11:10:00,917 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  10%|▉         | 19/200 [00:32<04:49,  1.60s/it]2026-05-11 11:10:02,426 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  10%|█         | 20/200 [00:33<04:42,  1.57s/it]2026-05-11 11:10:04,147 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  10%|█         | 21/200 [00:35<04:49,  1.62s/it]2026-05-11 11:10:05,550 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  11%|█         | 22/200 [00:36<04:36,  1.55s/it]2026-05-11 11:10:07,279 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  12%|█▏        | 23/200 [00:38<04:44,  1.61s/it]2026-05-11 11:10:08,934 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  12%|█▏        | 24/200 [00:40<04:45,  1.62s/it]2026-05-11 11:10:10,320 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  12%|█▎        | 25/200 [00:41<04:31,  1.55s/it]2026-05-11 11:10:11,705 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  13%|█▎        | 26/200 [00:42<04:21,  1.50s/it]2026-05-11 11:10:13,244 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  14%|█▎        | 27/200 [00:44<04:21,  1.51s/it]2026-05-11 11:10:14,785 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  14%|█▍        | 28/200 [00:45<04:21,  1.52s/it]2026-05-11 11:10:16,592 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  14%|█▍        | 29/200 [00:47<04:34,  1.61s/it]2026-05-11 11:10:18,456 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  15%|█▌        | 30/200 [00:49<04:46,  1.68s/it]2026-05-11 11:10:19,846 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  16%|█▌        | 31/200 [00:51<04:29,  1.60s/it]2026-05-11 11:10:21,674 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  16%|█▌        | 32/200 [00:52<04:39,  1.67s/it]2026-05-11 11:10:23,134 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  16%|█▋        | 33/200 [00:54<04:27,  1.60s/it]2026-05-11 11:10:24,585 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  17%|█▋        | 34/200 [00:55<04:18,  1.56s/it]2026-05-11 11:10:25,975 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  18%|█▊        | 35/200 [00:57<04:08,  1.51s/it]2026-05-11 11:10:27,707 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  18%|█▊        | 36/200 [00:58<04:18,  1.58s/it]2026-05-11 11:10:29,452 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  18%|█▊        | 37/200 [01:00<04:24,  1.63s/it]2026-05-11 11:10:31,162 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  19%|█▉        | 38/200 [01:02<04:27,  1.65s/it]2026-05-11 11:10:32,965 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  20%|█▉        | 39/200 [01:04<04:33,  1.70s/it]2026-05-11 11:10:34,404 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  20%|██        | 40/200 [01:05<04:19,  1.62s/it]2026-05-11 11:10:35,932 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  20%|██        | 41/200 [01:07<04:13,  1.59s/it]2026-05-11 11:10:37,907 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  21%|██        | 42/200 [01:09<04:29,  1.71s/it]2026-05-11 11:10:39,625 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  22%|██▏       | 43/200 [01:10<04:28,  1.71s/it]2026-05-11 11:10:41,077 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  22%|██▏       | 44/200 [01:12<04:14,  1.63s/it]2026-05-11 11:10:42,562 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  22%|██▎       | 45/200 [01:13<04:06,  1.59s/it]2026-05-11 11:10:44,312 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  23%|██▎       | 46/200 [01:15<04:12,  1.64s/it]2026-05-11 11:10:45,972 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  24%|██▎       | 47/200 [01:17<04:11,  1.64s/it]2026-05-11 11:10:47,831 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  24%|██▍       | 48/200 [01:19<04:19,  1.71s/it]2026-05-11 11:10:49,481 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  24%|██▍       | 49/200 [01:20<04:15,  1.69s/it]2026-05-11 11:10:51,012 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  25%|██▌       | 50/200 [01:22<04:06,  1.64s/it]2026-05-11 11:10:52,431 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  26%|██▌       | 51/200 [01:23<03:54,  1.58s/it]2026-05-11 11:10:54,022 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  26%|██▌       | 52/200 [01:25<03:53,  1.58s/it]2026-05-11 11:10:55,512 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  26%|██▋       | 53/200 [01:26<03:48,  1.55s/it]2026-05-11 11:10:57,019 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  27%|██▋       | 54/200 [01:28<03:44,  1.54s/it]2026-05-11 11:10:58,777 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  28%|██▊       | 55/200 [01:29<03:52,  1.61s/it]2026-05-11 11:11:00,254 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  28%|██▊       | 56/200 [01:31<03:45,  1.57s/it]2026-05-11 11:11:02,069 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  28%|██▊       | 57/200 [01:33<03:54,  1.64s/it]2026-05-11 11:11:03,631 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  29%|██▉       | 58/200 [01:34<03:49,  1.62s/it]2026-05-11 11:11:05,392 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  30%|██▉       | 59/200 [01:36<03:54,  1.66s/it]2026-05-11 11:11:07,476 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  30%|███       | 60/200 [01:38<04:10,  1.79s/it]2026-05-11 11:11:09,186 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  30%|███       | 61/200 [01:40<04:05,  1.76s/it]2026-05-11 11:11:10,677 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  31%|███       | 62/200 [01:41<03:52,  1.68s/it]2026-05-11 11:11:12,174 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  32%|███▏      | 63/200 [01:43<03:42,  1.63s/it]2026-05-11 11:11:13,993 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  32%|███▏      | 64/200 [01:45<03:49,  1.68s/it]2026-05-11 11:11:15,475 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  32%|███▎      | 65/200 [01:46<03:39,  1.62s/it]2026-05-11 11:11:16,915 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  33%|███▎      | 66/200 [01:48<03:30,  1.57s/it]2026-05-11 11:11:18,434 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  34%|███▎      | 67/200 [01:49<03:26,  1.55s/it]2026-05-11 11:11:20,121 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  34%|███▍      | 68/200 [01:51<03:30,  1.59s/it]2026-05-11 11:11:21,609 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  34%|███▍      | 69/200 [01:52<03:24,  1.56s/it]2026-05-11 11:11:23,024 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  35%|███▌      | 70/200 [01:54<03:17,  1.52s/it]2026-05-11 11:11:24,534 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  36%|███▌      | 71/200 [01:55<03:15,  1.52s/it]2026-05-11 11:11:25,860 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  36%|███▌      | 72/200 [01:57<03:06,  1.46s/it]2026-05-11 11:11:27,373 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  36%|███▋      | 73/200 [01:58<03:07,  1.47s/it]2026-05-11 11:11:28,866 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  37%|███▋      | 74/200 [02:00<03:06,  1.48s/it]2026-05-11 11:11:30,277 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  38%|███▊      | 75/200 [02:01<03:02,  1.46s/it]2026-05-11 11:11:31,885 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  38%|███▊      | 76/200 [02:03<03:06,  1.50s/it]2026-05-11 11:11:33,403 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  38%|███▊      | 77/200 [02:04<03:05,  1.51s/it]2026-05-11 11:11:34,893 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  39%|███▉      | 78/200 [02:06<03:03,  1.50s/it]2026-05-11 11:11:36,487 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  40%|███▉      | 79/200 [02:07<03:05,  1.53s/it]2026-05-11 11:11:38,142 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  40%|████      | 80/200 [02:09<03:08,  1.57s/it]2026-05-11 11:11:39,903 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  40%|████      | 81/200 [02:11<03:13,  1.63s/it]2026-05-11 11:11:41,455 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  41%|████      | 82/200 [02:12<03:09,  1.60s/it]2026-05-11 11:11:43,431 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  42%|████▏     | 83/200 [02:14<03:20,  1.72s/it]2026-05-11 11:11:44,979 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  42%|████▏     | 84/200 [02:16<03:13,  1.67s/it]2026-05-11 11:11:46,522 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  42%|████▎     | 85/200 [02:17<03:07,  1.63s/it]2026-05-11 11:11:48,024 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  43%|████▎     | 86/200 [02:19<03:01,  1.59s/it]2026-05-11 11:11:49,515 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  44%|████▎     | 87/200 [02:20<02:56,  1.56s/it]2026-05-11 11:11:51,015 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  44%|████▍     | 88/200 [02:22<02:52,  1.54s/it]2026-05-11 11:11:52,700 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  44%|████▍     | 89/200 [02:23<02:55,  1.59s/it]2026-05-11 11:11:54,018 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  45%|████▌     | 90/200 [02:25<02:45,  1.51s/it]2026-05-11 11:11:55,518 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  46%|████▌     | 91/200 [02:26<02:43,  1.50s/it]2026-05-11 11:11:57,032 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  46%|████▌     | 92/200 [02:28<02:42,  1.51s/it]2026-05-11 11:11:58,440 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  46%|████▋     | 93/200 [02:29<02:38,  1.48s/it]2026-05-11 11:11:59,877 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  47%|████▋     | 94/200 [02:31<02:35,  1.47s/it]2026-05-11 11:12:01,376 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  48%|████▊     | 95/200 [02:32<02:34,  1.48s/it]2026-05-11 11:12:02,938 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  48%|████▊     | 96/200 [02:34<02:36,  1.50s/it]2026-05-11 11:12:04,485 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  48%|████▊     | 97/200 [02:35<02:36,  1.52s/it]2026-05-11 11:12:06,250 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  49%|████▉     | 98/200 [02:37<02:42,  1.59s/it]2026-05-11 11:12:07,606 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  50%|████▉     | 99/200 [02:38<02:33,  1.52s/it]2026-05-11 11:12:09,266 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  50%|█████     | 100/200 [02:40<02:36,  1.56s/it]2026-05-11 11:12:11,089 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  50%|█████     | 101/200 [02:42<02:42,  1.64s/it]2026-05-11 11:12:12,739 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  51%|█████     | 102/200 [02:43<02:41,  1.64s/it]2026-05-11 11:12:14,317 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  52%|█████▏    | 103/200 [02:45<02:37,  1.62s/it]2026-05-11 11:12:15,931 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  52%|█████▏    | 104/200 [02:47<02:35,  1.62s/it]2026-05-11 11:12:17,513 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  52%|█████▎    | 105/200 [02:48<02:32,  1.61s/it]2026-05-11 11:12:19,601 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  53%|█████▎    | 106/200 [02:50<02:44,  1.75s/it]2026-05-11 11:12:20,926 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  54%|█████▎    | 107/200 [02:52<02:31,  1.62s/it]2026-05-11 11:12:22,659 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  54%|█████▍    | 108/200 [02:53<02:32,  1.66s/it]2026-05-11 11:12:24,334 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  55%|█████▍    | 109/200 [02:55<02:31,  1.66s/it]2026-05-11 11:12:26,084 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  55%|█████▌    | 110/200 [02:57<02:31,  1.69s/it]2026-05-11 11:12:27,497 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  56%|█████▌    | 111/200 [02:58<02:22,  1.61s/it]2026-05-11 11:12:29,152 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  56%|█████▌    | 112/200 [03:00<02:22,  1.62s/it]2026-05-11 11:12:30,983 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  56%|█████▋    | 113/200 [03:02<02:26,  1.68s/it]2026-05-11 11:12:32,403 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (few_shot):  57%|█████▋    | 114/200 [03:03<02:17,  1.60s/it]2026-05-11 11:12:34,413 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

=== Résultats Few-Shot ===
  mode                      : few_shot
  model                     : llama3.1:8b
  n_samples                 : 200
  top_k                     : 3
  accuracy_at_k             : 0.75
  top1_accuracy             : 0.535
  mrr_at_k                  : 0.6308333333333332
  empty_predictions         : 0
  time_seconds              : 324.3
  seconds_per_article       : 1.62

---
## 7b. Évaluation Few-Shot Dynamique (TF-IDF)

Pour chaque article, on sélectionne les **N articles les plus similaires** dans le train set via similarité cosine TF-IDF. Ces exemples pertinents et contextuels remplacent les exemples statiques du few-shot classique.

In [33]:
# ---- Évaluation Few-Shot Dynamique (TF-IDF) ----
logging.info(f"Lancement évaluation dynamic few-shot (top-{N_DYNAMIC_EXAMPLES}) sur {len(eval_data)} articles...")

results_dfs, preds_dfs = run_evaluation(
    eval_df=eval_data,
    categories=CATEGORIES,
    model=OLLAMA_MODEL,
    top_k=TOP_K,
    mode="dynamic_few_shot",
    n_dynamic=N_DYNAMIC_EXAMPLES
)

print("\n=== Résultats Few-Shot Dynamique (TF-IDF) ===")
for k, v in results_dfs.items():
    print(f"  {k:25s} : {v}")

2026-05-11 11:14:53,102 : INFO : Lancement évaluation dynamic few-shot (top-5) sur 200 articles...
Prédiction (dynamic_few_shot):   0%|          | 0/200 [00:00<?, ?it/s]2026-05-11 11:14:54,846 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   0%|          | 1/200 [00:01<05:46,  1.74s/it]2026-05-11 11:14:56,519 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   1%|          | 2/200 [00:03<05:36,  1.70s/it]2026-05-11 11:14:58,279 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   2%|▏         | 3/200 [00:05<05:40,  1.73s/it]2026-05-11 11:15:00,096 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   2%|▏         | 4/200 [00:06<05:45,  1.76s/it]2026-05-11 11:15:01,636 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   2%|▎         | 5/200 [00:08<05:28,  1.68s/it]2026-05-11 11:15:03,848 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   3%|▎         | 6/200 [00:10<06:01,  1.86s/it]2026-05-11 11:15:05,415 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   4%|▎         | 7/200 [00:12<05:40,  1.77s/it]2026-05-11 11:15:07,125 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   4%|▍         | 8/200 [00:14<05:35,  1.75s/it]2026-05-11 11:15:08,840 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   4%|▍         | 9/200 [00:15<05:31,  1.74s/it]2026-05-11 11:15:10,980 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   5%|▌         | 10/200 [00:17<05:53,  1.86s/it]2026-05-11 11:15:12,696 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   6%|▌         | 11/200 [00:19<05:43,  1.82s/it]2026-05-11 11:15:14,489 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   6%|▌         | 12/200 [00:21<05:40,  1.81s/it]2026-05-11 11:15:16,177 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   6%|▋         | 13/200 [00:23<05:31,  1.77s/it]2026-05-11 11:15:18,117 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   7%|▋         | 14/200 [00:25<05:39,  1.82s/it]2026-05-11 11:15:19,759 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   8%|▊         | 15/200 [00:26<05:27,  1.77s/it]2026-05-11 11:15:21,791 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   8%|▊         | 16/200 [00:28<05:40,  1.85s/it]2026-05-11 11:15:23,635 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   8%|▊         | 17/200 [00:30<05:37,  1.85s/it]2026-05-11 11:15:25,335 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):   9%|▉         | 18/200 [00:32<05:28,  1.80s/it]2026-05-11 11:15:26,852 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  10%|▉         | 19/200 [00:33<05:10,  1.72s/it]2026-05-11 11:15:28,765 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  10%|█         | 20/200 [00:35<05:19,  1.78s/it]2026-05-11 11:15:30,800 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  10%|█         | 21/200 [00:37<05:31,  1.85s/it]2026-05-11 11:15:32,660 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  11%|█         | 22/200 [00:39<05:30,  1.86s/it]2026-05-11 11:15:34,161 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  12%|█▏        | 23/200 [00:41<05:09,  1.75s/it]2026-05-11 11:15:35,966 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  12%|█▏        | 24/200 [00:42<05:10,  1.77s/it]2026-05-11 11:15:37,536 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  12%|█▎        | 25/200 [00:44<04:58,  1.71s/it]2026-05-11 11:15:39,304 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  13%|█▎        | 26/200 [00:46<05:00,  1.73s/it]2026-05-11 11:15:41,023 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  14%|█▎        | 27/200 [00:47<04:58,  1.72s/it]2026-05-11 11:15:42,874 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  14%|█▍        | 28/200 [00:49<05:03,  1.76s/it]2026-05-11 11:15:44,907 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  14%|█▍        | 29/200 [00:51<05:15,  1.84s/it]2026-05-11 11:15:46,633 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  15%|█▌        | 30/200 [00:53<05:07,  1.81s/it]2026-05-11 11:15:48,500 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  16%|█▌        | 31/200 [00:55<05:08,  1.83s/it]2026-05-11 11:15:50,432 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  16%|█▌        | 32/200 [00:57<05:12,  1.86s/it]2026-05-11 11:15:52,032 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  16%|█▋        | 33/200 [00:58<04:57,  1.78s/it]2026-05-11 11:15:53,502 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  17%|█▋        | 34/200 [01:00<04:40,  1.69s/it]2026-05-11 11:15:55,536 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  18%|█▊        | 35/200 [01:02<04:55,  1.79s/it]2026-05-11 11:15:57,315 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  18%|█▊        | 36/200 [01:04<04:53,  1.79s/it]2026-05-11 11:15:58,907 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  18%|█▊        | 37/200 [01:05<04:41,  1.73s/it]2026-05-11 11:16:00,414 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  19%|█▉        | 38/200 [01:07<04:29,  1.66s/it]2026-05-11 11:16:02,151 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  20%|█▉        | 39/200 [01:09<04:31,  1.68s/it]2026-05-11 11:16:03,938 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  20%|██        | 40/200 [01:10<04:34,  1.72s/it]2026-05-11 11:16:05,562 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  20%|██        | 41/200 [01:12<04:28,  1.69s/it]2026-05-11 11:16:07,719 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  21%|██        | 42/200 [01:14<04:48,  1.83s/it]2026-05-11 11:16:09,915 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  22%|██▏       | 43/200 [01:16<05:04,  1.94s/it]2026-05-11 11:16:11,461 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  22%|██▏       | 44/200 [01:18<04:44,  1.82s/it]2026-05-11 11:16:13,120 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  22%|██▎       | 45/200 [01:20<04:34,  1.77s/it]2026-05-11 11:16:15,345 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  23%|██▎       | 46/200 [01:22<04:53,  1.91s/it]2026-05-11 11:16:17,342 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  24%|██▎       | 47/200 [01:24<04:56,  1.93s/it]2026-05-11 11:16:19,419 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  24%|██▍       | 48/200 [01:26<05:00,  1.98s/it]2026-05-11 11:16:21,229 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  24%|██▍       | 49/200 [01:28<04:51,  1.93s/it]2026-05-11 11:16:22,735 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  25%|██▌       | 50/200 [01:29<04:30,  1.80s/it]2026-05-11 11:16:24,756 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  26%|██▌       | 51/200 [01:31<04:38,  1.87s/it]2026-05-11 11:16:26,509 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  26%|██▌       | 52/200 [01:33<04:31,  1.83s/it]2026-05-11 11:16:28,718 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  26%|██▋       | 53/200 [01:35<04:46,  1.95s/it]2026-05-11 11:16:30,404 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  27%|██▋       | 54/200 [01:37<04:32,  1.87s/it]2026-05-11 11:16:32,279 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  28%|██▊       | 55/200 [01:39<04:31,  1.87s/it]2026-05-11 11:16:33,844 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  28%|██▊       | 56/200 [01:40<04:16,  1.78s/it]2026-05-11 11:16:35,701 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  28%|██▊       | 57/200 [01:42<04:17,  1.80s/it]2026-05-11 11:16:37,406 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  29%|██▉       | 58/200 [01:44<04:11,  1.77s/it]2026-05-11 11:16:39,299 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  30%|██▉       | 59/200 [01:46<04:15,  1.81s/it]2026-05-11 11:16:41,432 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  30%|███       | 60/200 [01:48<04:26,  1.91s/it]2026-05-11 11:16:43,230 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  30%|███       | 61/200 [01:50<04:20,  1.87s/it]2026-05-11 11:16:45,006 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  31%|███       | 62/200 [01:51<04:14,  1.84s/it]2026-05-11 11:16:47,062 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  32%|███▏      | 63/200 [01:53<04:21,  1.91s/it]2026-05-11 11:16:49,181 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  32%|███▏      | 64/200 [01:56<04:28,  1.97s/it]2026-05-11 11:16:50,698 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  32%|███▎      | 65/200 [01:57<04:07,  1.83s/it]2026-05-11 11:16:52,743 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  33%|███▎      | 66/200 [01:59<04:14,  1.90s/it]2026-05-11 11:16:54,793 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  34%|███▎      | 67/200 [02:01<04:18,  1.94s/it]2026-05-11 11:16:56,206 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  34%|███▍      | 68/200 [02:03<03:55,  1.78s/it]2026-05-11 11:16:57,730 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  34%|███▍      | 69/200 [02:04<03:43,  1.71s/it]2026-05-11 11:16:59,148 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  35%|███▌      | 70/200 [02:06<03:30,  1.62s/it]2026-05-11 11:17:00,851 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  36%|███▌      | 71/200 [02:07<03:32,  1.64s/it]2026-05-11 11:17:02,317 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  36%|███▌      | 72/200 [02:09<03:23,  1.59s/it]2026-05-11 11:17:03,817 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  36%|███▋      | 73/200 [02:10<03:18,  1.56s/it]2026-05-11 11:17:05,394 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  37%|███▋      | 74/200 [02:12<03:17,  1.57s/it]2026-05-11 11:17:06,899 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  38%|███▊      | 75/200 [02:13<03:13,  1.55s/it]2026-05-11 11:17:08,742 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  38%|███▊      | 76/200 [02:15<03:22,  1.64s/it]2026-05-11 11:17:10,430 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  38%|███▊      | 77/200 [02:17<03:23,  1.65s/it]2026-05-11 11:17:12,321 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  39%|███▉      | 78/200 [02:19<03:30,  1.72s/it]2026-05-11 11:17:13,901 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  40%|███▉      | 79/200 [02:20<03:23,  1.68s/it]2026-05-11 11:17:15,767 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  40%|████      | 80/200 [02:22<03:28,  1.74s/it]2026-05-11 11:17:17,908 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  40%|████      | 81/200 [02:24<03:41,  1.86s/it]2026-05-11 11:17:19,575 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  41%|████      | 82/200 [02:26<03:32,  1.80s/it]2026-05-11 11:17:21,306 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  42%|████▏     | 83/200 [02:28<03:28,  1.78s/it]2026-05-11 11:17:23,205 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  42%|████▏     | 84/200 [02:30<03:30,  1.82s/it]2026-05-11 11:17:24,755 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  42%|████▎     | 85/200 [02:31<03:19,  1.74s/it]2026-05-11 11:17:26,254 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  43%|████▎     | 86/200 [02:33<03:09,  1.66s/it]2026-05-11 11:17:27,866 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  44%|████▎     | 87/200 [02:34<03:06,  1.65s/it]2026-05-11 11:17:29,760 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  44%|████▍     | 88/200 [02:36<03:12,  1.72s/it]2026-05-11 11:17:31,582 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  44%|████▍     | 89/200 [02:38<03:14,  1.75s/it]2026-05-11 11:17:33,104 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  45%|████▌     | 90/200 [02:39<03:05,  1.68s/it]2026-05-11 11:17:34,617 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  46%|████▌     | 91/200 [02:41<02:57,  1.63s/it]2026-05-11 11:17:36,120 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  46%|████▌     | 92/200 [02:43<02:52,  1.59s/it]2026-05-11 11:17:37,651 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  46%|████▋     | 93/200 [02:44<02:48,  1.57s/it]2026-05-11 11:17:39,151 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  47%|████▋     | 94/200 [02:46<02:44,  1.55s/it]2026-05-11 11:17:40,634 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  48%|████▊     | 95/200 [02:47<02:40,  1.53s/it]2026-05-11 11:17:42,558 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  48%|████▊     | 96/200 [02:49<02:51,  1.65s/it]2026-05-11 11:17:44,196 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  48%|████▊     | 97/200 [02:51<02:49,  1.65s/it]2026-05-11 11:17:46,123 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  49%|████▉     | 98/200 [02:53<02:56,  1.73s/it]2026-05-11 11:17:47,506 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  50%|████▉     | 99/200 [02:54<02:44,  1.63s/it]2026-05-11 11:17:49,281 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  50%|█████     | 100/200 [02:56<02:47,  1.67s/it]2026-05-11 11:17:51,047 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  50%|█████     | 101/200 [02:57<02:48,  1.70s/it]2026-05-11 11:17:52,709 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  51%|█████     | 102/200 [02:59<02:45,  1.69s/it]2026-05-11 11:17:54,587 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  52%|█████▏    | 103/200 [03:01<02:49,  1.75s/it]2026-05-11 11:17:56,509 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  52%|█████▏    | 104/200 [03:03<02:52,  1.80s/it]2026-05-11 11:17:58,007 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  52%|█████▎    | 105/200 [03:04<02:42,  1.71s/it]2026-05-11 11:18:00,215 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  53%|█████▎    | 106/200 [03:07<02:54,  1.86s/it]2026-05-11 11:18:02,070 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  54%|█████▎    | 107/200 [03:08<02:52,  1.86s/it]2026-05-11 11:18:04,024 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Prédiction (dynamic_few_shot):  54%|█████▍    | 108/200 [03:10<02:53,  1.89s/it]2026-05-11 11:18:06,010 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

=== Résultats Few-Shot Dynamique (TF-IDF) ===
  mode                      : dynamic_few_shot
  model                     : llama3.1:8b
  n_samples                 : 200
  top_k                     : 3
  accuracy_at_k             : 0.835
  top1_accuracy             : 0.605
  mrr_at_k                  : 0.7099999999999999
  empty_predictions         : 0
  time_seconds              : 354.4
  seconds_per_article       : 1.77

---
## 8. Comparaison des résultats

In [34]:
df_results = pd.DataFrame([results_zs, results_fs, results_dfs])
df_results = df_results[['mode', 'model', 'n_samples', 'top_k', 'top1_accuracy',
                          'accuracy_at_k', 'mrr_at_k', 'empty_predictions',
                          'time_seconds', 'seconds_per_article']]
df_results

,mode,model,n_samples,top_k,top1_accuracy,accuracy_at_k,mrr_at_k,empty_predictions,time_seconds,seconds_per_article
0,zero_shot,llama3.1:8b,200,3,0.510,0.720,0.595833,0,353.1,1.77
1,few_shot,llama3.1:8b,200,3,0.535,0.750,0.630833,0,324.3,1.62
2,dynamic_few_shot,llama3.1:8b,200,3,0.605,0.835,0.710000,0,354.4,1.77

### Analyse des erreurs

In [35]:
eval_data_analysis = eval_data.copy()
eval_data_analysis['preds_zero_shot'] = preds_zs
eval_data_analysis['preds_few_shot'] = preds_fs
eval_data_analysis['preds_dynamic'] = preds_dfs

for col, preds_col in [('correct_zs', 'preds_zero_shot'),
                        ('correct_fs', 'preds_few_shot'),
                        ('correct_dfs', 'preds_dynamic')]:
    eval_data_analysis[col] = eval_data_analysis.apply(
        lambda r, pc=preds_col: r['category'] in r[pc], axis=1
    )

cat_accuracy = eval_data_analysis.groupby('category')[['correct_zs', 'correct_fs', 'correct_dfs']].mean()
cat_accuracy.columns = ['zero_shot', 'few_shot', 'dynamic_few_shot']
cat_accuracy = cat_accuracy.sort_values('zero_shot', ascending=False)
print("Accuracy par catégorie (top-k) :")
print(cat_accuracy.to_string())

Accuracy par catégorie (top-k) :
                zero_shot  few_shot  dynamic_few_shot
category
ARTS             1.000000  1.000000          0.500000
ARTS & CULTURE   1.000000  0.500000          0.500000
BUSINESS         1.000000  0.750000          0.750000
GOOD NEWS        1.000000  1.000000          1.000000
SPORTS           1.000000  1.000000          1.000000
LATINO VOICES    1.000000  1.000000          1.000000
STYLE            1.000000  1.000000          1.000000
TASTE            1.000000  1.000000          0.000000
TECH             1.000000  1.000000          1.000000
WORLD NEWS       1.000000  1.000000          0.833333
SCIENCE          1.000000  1.000000          1.000000
POLITICS         0.927273  0.981818          0.963636
ENTERTAINMENT    0.909091  0.863636          0.954545
CRIME            0.750000  0.500000          0.750000
HEALTHY LIVING   0.727273  0.818182          0.818182
WEIRD NEWS       0.666667  0.333333          0.666667
QUEER VOICES     0.666667  0.733333          0.866667
RELIGION         0.600000  0.600000          0.800000
COMEDY           0.600000  0.400000          0.800000
COLLEGE          0.500000  0.500000          0.500000
TRAVEL           0.500000  0.750000          1.000000
PARENTS          0.428571  0.571429          0.571429
BLACK VOICES     0.416667  0.166667          0.833333
IMPACT           0.333333  0.833333          0.333333
MEDIA            0.250000  0.500000          0.750000
EDUCATION        0.000000  0.000000          0.000000
GREEN            0.000000  0.000000          0.000000
FIFTY            0.000000  0.000000          0.333333
WOMEN            0.000000  1.000000          1.000000
WORLDPOST        0.000000  0.000000          0.666667

In [36]:
# Exemples d'erreurs
errors = eval_data_analysis[~eval_data_analysis['correct_zs']].head(10)
print("Exemples d'erreurs (zero-shot) :\n")
for _, row in errors.iterrows():
    print(f"  Texte  : {row['text'][:120]}...")
    print(f"  Vrai   : {row['category']}")
    print(f"  Prédit : {row['preds_zero_shot']}")
    print()

Exemples d'erreurs (zero-shot) :

  Texte  : The Smartest Thing I've Ever Read About Consent. Cathy Young's recent piece in the Washington Post, "Feminists want us t...
  Vrai   : EDUCATION
  Prédit : ['WOMEN', 'ARTS & CULTURE', 'POLITICS']

  Texte  : A Carol for Our Times: The Melrose Quartet Perform 'Sing John Ball' (VIDEO). As a music journalist it may seem out of pl...
  Vrai   : RELIGION
  Prédit : ['ARTS & CULTURE', 'ENTERTAINMENT']

  Texte  : Frequencies: Law of Attraction. I've noticed that as soon as I allow myself to worry about something, it begins to take ...
  Vrai   : COLLEGE
  Prédit : ['HEALTHY LIVING', 'ARTS & CULTURE', 'STYLE']

  Texte  : John Oliver Calls Out The Academy For Hypocrisy After Weinstein Decision. The "Last Week Tonight" host takes on Hollywoo...
  Vrai   : COMEDY
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'POLITICS']

  Texte  : RuPaul Is Getting A Star On The Walk Of Fame. Shantay, you stay!...
  Vrai   : QUEER VOICES
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'STYLE']

  Texte  : Ode to Football: A Sport I Kind of Can't Stand. I revere football because it provides an opportunity in pop culture to w...
  Vrai   : QUEER VOICES
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'COMEDY']

  Texte  : Social Equality: The Best Cure for Uterine Prolapse in Nepal. In November of 1987, I gave birth in the plains of Nepal. ...
  Vrai   : IMPACT
  Prédit : ['WORLD NEWS', 'GOOD NEWS', 'HEALTHY LIVING']

  Texte  : Two Police Officers Stabbed In Belgium In Possible Extremist Attack. Counter terror prosecutors have stepped in to inves...
  Vrai   : WORLDPOST
  Prédit : ['WORLD NEWS', 'CRIME', 'IMPACT']

  Texte  : Meet The 70-Year-Old Hiking The Pacific Crest Trail. My friend Tony and I just returned from meeting up with our friend ...
  Vrai   : FIFTY
  Prédit : ['TRAVEL', 'SPORTS', 'GOOD NEWS']

  Texte  : The 20 Funniest Tweets From Women This Week. The ladies of Twitter never fail to brighten our days with their brilliant ...
  Vrai   : WOMEN
  Prédit : ['ENTERTAINMENT', 'ARTS & CULTURE', 'COMEDY']

---
## 9. Prédictions sur articles CNN (non vus) — comme le notebook de référence

In [37]:
cnn_articles = [
    {
        "source": "https://www.cnn.com/2019/07/19/politics/george-nader-child-porn-sex-charges/",
        "text": "George Aref Nader, who was a key witness in special counsel Robert Mueller's Russia investigation, faces new charges of transporting a minor with intent to engage in criminal sexual activity and child pornography"
    },
    {
        "source": "https://www.cnn.com/2019/07/18/entertainment/khloe-kardashian-true-thompson-video-trnd/",
        "text": "True Thompson makes an adorable cameo in Khloe Kardashian's new makeup tutorial video"
    },
    {
        "source": "https://www.cnn.com/2019/07/12/entertainment/heidi-klum-tom-kaulitz/",
        "text": "Heidi Klum is apparently the latest celeb to get married and not tell us"
    },
    {
        "source": "https://www.cnn.com/2019/07/19/investing/dow-stock-market-today/",
        "text": "Stocks end lower as geopolitical fears rise. The Dow and US markets closed lower on Friday, as geopolitical worries overshadowed the hopes of interest rate cuts by the Federal Reserve."
    },
    {
        "source": "https://www.cnn.com/2019/07/19/health/astronaut-exercise-iv-faint-scn/",
        "text": "Exercise in space keeps astronauts from fainting when they return to Earth, study says."
    },
]

print("=== Prédictions sur articles CNN (zero-shot) ===\n")
for article in cnn_articles:
    preds = predict_with_ollama(article['text'], CATEGORIES, top_k=TOP_K, mode="zero_shot")
    print(f"  Article : {article['text'][:100]}...")
    print(f"  Top-{TOP_K}  : {preds}")
    print()

=== Prédictions sur articles CNN (zero-shot) ===

2026-05-11 11:20:49,567 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

  Article : George Aref Nader, who was a key witness in special counsel Robert Mueller's Russia investigation, f...
  Top-3  : ['CRIME', 'WORLD NEWS', 'POLITICS']

2026-05-11 11:20:51,649 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

  Article : True Thompson makes an adorable cameo in Khloe Kardashian's new makeup tutorial video...
  Top-3  : ['ENTERTAINMENT', 'STYLE', 'ARTS & CULTURE']

2026-05-11 11:20:53,169 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

  Article : Heidi Klum is apparently the latest celeb to get married and not tell us...
  Top-3  : ['ENTERTAINMENT', 'STYLE', 'WOMEN']

2026-05-11 11:20:55,204 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

  Article : Stocks end lower as geopolitical fears rise. The Dow and US markets closed lower on Friday, as geopo...
  Top-3  : ['BUSINESS', 'POLITICS', 'WORLD NEWS']

2026-05-11 11:20:56,953 : INFO : HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

  Article : Exercise in space keeps astronauts from fainting when they return to Earth, study says....
  Top-3  : ['SCIENCE', 'HEALTHY LIVING', 'WORLD NEWS']

---
## 11. Sauvegarde des résultats

In [39]:
output_path = r"C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\results\llm_evaluation_results.json"

import os
os.makedirs(os.path.dirname(output_path), exist_ok=True)

results_to_save = {
    "zero_shot": results_zs,
    "few_shot": results_fs,
    "dynamic_few_shot": results_dfs,
    "config": {
        "model": OLLAMA_MODEL,
        "eval_sample_size": EVAL_SAMPLE_SIZE,
        "top_k": TOP_K,
        "n_categories": len(CATEGORIES),
        "n_dynamic_examples": N_DYNAMIC_EXAMPLES,
    }
}

with open(output_path, 'w') as f:
    json.dump(results_to_save, f, indent=2)

print(f"Résultats sauvegardés dans {output_path}")

Résultats sauvegardés dans C:\Users\jfurs\Pythonn\OpenClassrooms\DS\P8\high_end_ollama_solution\results\llm_evaluation_results.json

---
## Résumé

| Aspect | Notebook NLP (référence) | Notebook LLM (Ollama) |
|--------|--------------------------|------------------------|
| **Features** | TF-IDF / Binary / Counts | Texte brut envoyé au LLM |
| **Modèle** | Logistic Regression (sklearn) | LLM local (Ollama) |
| **Entraînement** | Nécessaire (fit sur train set) | Aucun (zero-shot) ou quelques exemples (few-shot) |
| **Vitesse** | Très rapide (~secondes) | Lent (~1-5s par article) |
| **Flexibilité** | Fixé aux catégories du train | Peut classifier vers de nouvelles catégories |
| **Évaluation** | Accuracy + MRR@k | Accuracy + MRR@k (identique) |